
const languagesDefault = [
    {"lang":"Afrikaans","symbol":"AF", "iso1":"af","direction":"in"},
    {"lang":"Arabic","symbol":"AR","direction":"both","dialects":[{"lang":"Arabic (Saudi Arabia)","symbol":"AR-SA","direction":"in", "check": false},{"lang":"Arabic (Egypt)","symbol":"AR-EG","direction":"in", "check": false},{"lang":"Arabic (Morocco)","symbol":"AR-MA","direction":"in", "check": false}]},
    {"lang":"Azerbaijani (Latin)","symbol":"AZ-LN","direction":"in"},
    {"lang":"Bulgarian","symbol":"BG","direction":"both"},
    {"lang":"Bengali (Indida)","symbol":"BN-IN","direction":"in"},
    {"lang":"Bosnian","symbol":"BS","direction":"in"},
    {"lang":"Czech","symbol":"CS","direction":"in"},
    {"lang":"Danish","symbol":"DA","direction":"both"},
    {"lang":"Dutch","symbol":"NL","direction":"both","dialects":[{"lang":"Dutch (Netherlands)","symbol":"NL-NL","direction":"both", "check": false},{"lang":"Flemish","symbol":"NL-BE","direction":"both", "check": false}]},    
    {"lang":"German","symbol":"DE","diraction":"both","dialects":[{"lang":"German (Germany)","symbol":"DE-DE","direction":"both", "check": false},{"lang":"German (Austria)","symbol":"DE-AT","direction":"both", "check": false},{"lang":"German (Switzerland)","symbol":"DE-CH","direction":"both", "check": false}]},
    {"lang":"Greek","symbol":"EL","direction":"both"},
    {"lang":"English","symbol":"EN","direction":"both","dialects":[{"lang":"English (United Kingdom)","symbol":"EN-GB","direction":"both", "check": false},{"lang":"English (United States)","symbol":"EN-US","direction":"both", "check": false}]},
    {"lang":"Spanish (Spain)","symbol":"ES-ES","direction":"both"},
    {"lang":"Spanish (Latin America)","direction":"in","symbol":"ES-419","dialects":[{"lang":"Spanish (Argentina)","symbol":"ES-AR","direction":"in", "check": false},{"lang":"Spanish (Mexico)","symbol":"ES-MX","direction":"both", "check": false}]},
    {"lang":"Estonian","symbol":"ET","direction":"both"},
    {"lang":"Farsi (Persian)","symbol":"FA","direction":"both"},
    {"lang":"Finnish","symbol":"FI","direction":"both"},
    {"lang":"French","symbol":"FR","direction":"both","dialects":[{"lang":"French (France)","symbol":"FR-FR","direction":"both", "check": false},{"lang":"French (Belgium)","symbol":"FR-BE","direction":"both", "check": false},{"lang":"French (Canada)","symbol":"FR-CA","direction":"in", "check": false},{"lang":"French (Switzerland)","symbol":"FR-CH","direction":"in", "check": false}]},
    {"lang":"Hebrew","symbol":"HE","direction":"both"},
    {"lang":"Hindi","symbol":"HI","direction":"in"},
    {"lang":"Croatian","symbol":"HR","direction":"in"},
    {"lang":"Hungarian","symbol":"HU","direction":"in"},
    {"lang":"Armenian","symbol":"HY","direction":"both"},
    {"lang":"Indonesian","symbol":"ID","direction":"both"},
    {"lang":"Icelandic","symbol":"IS","direction":"both"},
    {"lang":"Italian","symbol":"IT","direction":"in","dialects":[{"lang":"Italian (Italy)","symbol":"IT-IT","direction":"in", "check": false},{"lang":"Italian (Switzerland)","symbol":"IT-CH","direction":"in", "check": false}]},
    {"lang":"Japanese","symbol":"JA","direction":"in"},
    {"lang":"Georgian","symbol":"KA","direction":"in"},
    {"lang":"Kazakh","symbol":"KK","direction":"in"},
    {"lang":"Korean","symbol":"KO","direction":"in"},
    {"lang":"Lithuanian","symbol":"LT","direction":"in"},
    {"lang":"Latvian","symbol":"LV","direction":"in"},
    {"lang":"Moldavian","symbol":"MO","direction":"both"},
    {"lang":"Marathi","symbol":"MR","direction":"both"},
    {"lang":"Malay","symbol":"MS","direction":"both"},
    {"lang":"Norwegian (Bokmaal)","symbol":"NB","direction":"in"},
    {"lang":"Punjabi","symbol":"PA","direction":"both"},
    {"lang":"Polish","symbol":"PL","direction":"in"},
    {"lang":"Portuguese (Brazil)","symbol":"PT-BR","direction":"both"},
    {"lang":"Portuguese (Portugal)","symbol":"PT-PT","direction":"in"},
    {"lang":"Romanian","symbol":"RO","direction":"in"},
    {"lang":"Russian","symbol":"RU","direction":"in"},
    {"lang":"Slovak","symbol":"SK","direction":"both"},
    {"lang":"Slovenian","symbol":"SL","direction":"in"},
    {"lang":"Serbian (Latin)","symbol":"SR-LA","direction":"in"},
    {"lang":"Swedish (Sweden)","symbol":"SV-SE","direction":"in"},
    {"lang":"Telugu","symbol":"TE","direction":"in"},
    {"lang":"Thai","symbol":"TH","direction":"both"},
    {"lang":"Turkmen","symbol":"TK","direction":"in"},
    {"lang":"Tagalog","symbol":"TL","direction":"in"},
    {"lang":"Turkish","symbol":"TR","direction":"in"},
    {"lang":"Ukrainian","symbol":"UK","direction":"in"},
    {"lang":"Urdu","symbol":"UR","direction":"in"},
    {"lang":"Uzbek","symbol":"UZ","direction":"in"},
    {"lang":"Vietnamese","symbol":"VI","direction":"in"},
    {"lang":"Chinese Simplified","symbol":"ZH-CN","direction":"in","dialects":[{"lang":"Chinese (China)","symbol":"ZH-CN","direction":"in", "check": false},{"lang":"Chinese (Singapore)","symbol":"ZH-SG","direction":"in", "check": false}]},
    {"lang":"Chinese Traditional","symbol":"ZH-CN","direction":"in","dialects":[{"lang":"Chinese (Hong Kong)","symbol":"ZH-HK","direction":"in", "check": false},{"lang":"Chinese (Macao)","symbol":"ZH-MO","direction":"in"},{"lang":"Chinese (Taiwan)","symbol":"ZH-TW","direction":"in", "check": false}]},
];
const requestsDefault = [
    {
        date: new Date(new Date().setMonth(new Date().getMonth() - 1)),
        contactName: "Jhon",
        contactEmail: "jhon@email.com", 
        service: {title: "Translation"}, 
        industry: "Games", 
        status: "Open", 
        accountManager: "manager1", 
        web: "ap.com", 
        skype: "asd", 
        phone: "123456789", 
        companyName: "Apple"
    },
    { 
        date: new Date(new Date().setMonth(new Date().getMonth() - 2)), 
        contactName: "Elen", 
        contactEmail: "elen@email.com", 
        service: {title: "Design"}, 
        industry: "Real Estate", 
        status: "Canceled", 
        accountManager: "manager2", 
        web: "sam.com", 
        skype: "qwe", 
        phone: "123456789", 
        companyName: "Samsung" 
    },
    { 
        date: new Date(new Date().setMonth(new Date().getMonth() - 3)), 
        contactName: "Andrew", 
        contactEmail: "andrew@email.com", 
        service: {title: "Translation"}, 
        industry: "Casino", 
        status: "Assigned", 
        accountManager: "manager2", 
        web: "ea.com", 
        skype: "gfd", 
        phone: "123456789", 
        companyName: "EA-Sports" 
    },
    { 
        date: new Date(new Date().setMonth(new Date().getMonth() - 4)), 
        contactName: "George", 
        contactEmail: "george@email.com", 
        service: {title: "Copywriting"}, 
        industry: "Other", 
        status: "Close", 
        accountManager: "manager1", 
        web: "vul.com", 
        skype: "hgfd", 
        phone: "123456789", 
        companyName: "Vulcan" 
    },
    { 
        date: new Date(new Date().setMonth(new Date().getMonth() - 5)), 
        contactName: "Mike", 
        contactEmail: "mike@email.com", 
        service: {title: "Graphic design"}, 
        industry: "Cryptocurrency", 
        status: "Assigned", 
        accountManager: "manager1", 
        web: "cont.com", 
        skype: "rty", 
        phone: "123456879", 
        companyName: "Continental" },
    { 
        date: new Date(new Date().setMonth(new Date().getMonth())), 
        contactName: "Nathan", 
        contactEmail: "nathan@email.com", 
        service: {title: "Copywriting"}, 
        industry: "Games", 
        status: "New", 
        accountManager: "manager3", 
        web: "ms.com", 
        skype: "uyuyu", 
        phone: "123456789", 
        companyName: "Microsoft" 
    }            
];
const usersDefault = [
    { email: 'test@test.com', password: '12345', username: 'Petia' }
];

const servicesDefault = [
    {sortIndex: 1, xtrf: 11, projectType: "regular", title: "Translation", source: true, languages: {source: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH"], target: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH", "AF", "AR-EG", "AR-MA", "AR-SA", "AZ-LN", "BN-IN", "BS", "CS", "ES-419", "ES-AR", "FR-CA", "FR-CH", "HI", "HR", "HU", "IT", "IT-IT", "IT-CH", "JA", "KA", "KK", "KO", "LT", "LV", "NB", "NL", "PL", "PT-PT", "RO", "RU", "SL", "SR-LA", "SV-SE", "TE", "TK", "TL", "TR", "UK", "UR", "UZ", "VI", "ZH-CN", "ZH-SG", "ZH-HK", "ZH-MO", "ZH-TW"]}},
    {sortIndex: 2, xtrf: 11, projectType: "regular", title: "Localization", source: true, languages: {source: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH"], target: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH", "AF", "AR-EG", "AR-MA", "AR-SA", "AZ-LN", "BN-IN", "BS", "CS", "ES-419", "ES-AR", "FR-CA", "FR-CH", "HI", "HR", "HU", "IT", "IT-IT", "IT-CH", "JA", "KA", "KK", "KO", "LT", "LV", "NB", "NL", "PL", "PT-PT", "RO", "RU", "SL", "SR-LA", "SV-SE", "TE", "TK", "TL", "TR", "UK", "UR", "UZ", "VI", "ZH-CN", "ZH-SG", "ZH-HK", "ZH-MO", "ZH-TW"]}},
    {sortIndex: 3, xtrf: 35, projectType: "smart", title: "Proofing", source: true, languages: {source: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH"], target: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH", "AF", "AR-EG", "AR-MA", "AR-SA", "AZ-LN", "BN-IN", "BS", "CS", "ES-419", "ES-AR", "FR-CA", "FR-CH", "HI", "HR", "HU", "IT", "IT-IT", "IT-CH", "JA", "KA", "KK", "KO", "LT", "LV", "NB", "NL", "PL", "PT-PT", "RO", "RU", "SL", "SR-LA", "SV-SE", "TE", "TK", "TL", "TR", "UK", "UR", "UZ", "VI", "ZH-CN", "ZH-SG", "ZH-HK", "ZH-MO", "ZH-TW"]}},
    {sortIndex: 6, xtrf: 11, projectType: "regular", title: "SEO Translation", source: true, languages: {source: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH"], target: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH", "AF", "AR-EG", "AR-MA", "AR-SA", "AZ-LN", "BN-IN", "BS", "CS", "ES-419", "ES-AR", "FR-CA", "FR-CH", "HI", "HR", "HU", "IT", "IT-IT", "IT-CH", "JA", "KA", "KK", "KO", "LT", "LV", "NB", "NL", "PL", "PT-PT", "RO", "RU", "SL", "SR-LA", "SV-SE", "TE", "TK", "TL", "TR", "UK", "UR", "UZ", "VI", "ZH-CN", "ZH-SG", "ZH-HK", "ZH-MO", "ZH-TW"]}},
    {sortIndex: 8, xtrf: 12, projectType: "smart", title: "QA and Testing", source: true, languages: {source: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH"], target: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH", "AF", "AR-EG", "AR-MA", "AR-SA", "AZ-LN", "BN-IN", "BS", "CS", "ES-419", "ES-AR", "FR-CA", "FR-CH", "HI", "HR", "HU", "IT", "IT-IT", "IT-CH", "JA", "KA", "KK", "KO", "LT", "LV", "NB", "NL", "PL", "PT-PT", "RO", "RU", "SL", "SR-LA", "SV-SE", "TE", "TK", "TL", "TR", "UK", "UR", "UZ", "VI", "ZH-CN", "ZH-SG", "ZH-HK", "ZH-MO", "ZH-TW"]}},
    {sortIndex: 9, xtrf: 25, projectType: "smart", title: "Graphic Localization", source: true, languages: {source: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH"], target: ["AR", "BG", "DA", "DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "ET", "FA", "FI", "FR", "FR-FR", "FR-BE", "HE", "HY", "ID", "IS", "MO", "MR", "MS", "NL-NL", "NL-BE", "PA", "PT-BR", "SK", "TH", "AF", "AR-EG", "AR-MA", "AR-SA", "AZ-LN", "BN-IN", "BS", "CS", "ES-419", "ES-AR", "FR-CA", "FR-CH", "HI", "HR", "HU", "IT", "IT-IT", "IT-CH", "JA", "KA", "KK", "KO", "LT", "LV", "NB", "NL", "PL", "PT-PT", "RO", "RU", "SL", "SR-LA", "SV-SE", "TE", "TK", "TL", "TR", "UK", "UR", "UZ", "VI", "ZH-CN", "ZH-SG", "ZH-HK", "ZH-MO", "ZH-TW"]}},
    {sortIndex: 4, xtrf: 13, projectType: "smart", title: "Copywriting", source: false, languages: {source: [], target: ["AR", "AR-EG", "AR-SA", "AR-MA", "DE", "EN", "EN-GB", "EN-US", "ES-ES", "ES-419", "ES-AR", "ES-MX", "FR", "FR-FR", "HE", "IT", "IT-IT", "JA", "NB", "NL", "NL-NL", "PL", "RU", "SV-SE", "TR"]}},
    {sortIndex: 5, xtrf: 13, projectType: "smart", title: "Blogging", source: false, languages: {source: [], target: ["AR", "AR-EG", "AR-SA", "AR-MA", "DE", "EN", "EN-GB", "EN-US", "ES-ES", "ES-419", "ES-AR", "ES-MX", "FR", "FR-FR", "HE", "IT", "IT-IT", "JA", "NB", "NL", "NL-NL", "PL", "RU", "SV-SE", "TR"]}},
    {sortIndex: 7, xtrf: 13, projectType: "smart", title: "SEO Writing", source: false, languages: {source: [], target: ["AR", "AR-EG", "AR-SA", "AR-MA", "DE", "EN", "EN-GB", "EN-US", "ES-ES", "ES-419", "ES-AR", "ES-MX", "FR", "FR-FR", "HE", "IT", "IT-IT", "JA", "NB", "NL", "NL-NL", "PL", "RU", "SV-SE", "TR"]}},
    {sortIndex: 10, xtrf: 11, projectType: "regular", title: "Official Translation", source: true, languages: {source: ["DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "FR", "FR-FR", "FR-BE", "HE", "NL-NL", "NL-BE", "PT-BR", "TH"], target: ["DE", "DE-DE", "DE-AT", "DE-CH", "EL", "EN", "EN-GB", "EN-US", "ES-ES", "ES-MX", "FR", "FR-FR", "FR-BE", "HE", "NL-NL", "NL-BE", "PT-BR", "ES-419", "ES-AR", "FR-CA", "FR-CH", "IT", "IT-IT", "IT-CH", "NB", "NL", "PL", "RO", "RU"]}},
];

const industriesDefault = [
    {name: 'CASINO, POKER & IGAMING', icon: '/static/industries/casino-poker-igaming.png', download: '/static/Download-icon.png', generic: '/static/example.xlsx', active: true},
    {name: 'CFDS & ONLINE TRADING', icon: '/static/industries/cfds-online-tranding.png', download: '/static/Download-icon.png', generic: '/static/example.xlsx',active: true},
    {name: 'HOTEL & REAL ESTATES', icon: '/static/industries/hotel-real-estates.png', download: '/static/Download-icon.png', generic: '/static/example.xlsx', active: true},
    {name: 'ICOS & CRYPTOCURRENCY', icon: '/static/industries/icos-cryptocurrency.png', download: '/static/Download-icon.png', generic: '/static/example.xlsx', active: true},
    {name: 'LEGAL', icon: '/static/industries/legal-icon.png', download: '/static/Download-icon.png', generic: '/static/example.xlsx', active: true},
    {name: 'VIDEO GAMES', icon: '/static/industries/video-games.png', download: '/static/Download-icon.png', generic: ['/static/example.xlsx'], active: true},
    {name: 'MORE', icon: '/static/industries/more-icon.png', download: '/static/Download-icon.png', generic: '/static/example.xlsx', active: true}
];

const defaultValue = {
    languagesDefault,
    requestsDefault,
    usersDefault,
    servicesDefault,
    industriesDefault
};


module.exports = defaultValue;