const { User, Industries, Clients } = require('../../models');
const ObjectId = require('mongodb').ObjectID;
const clients = [
  {
    "ID": "C000003",
    "Name": "NetoMedia",
    "Legal Name [Official Company Name]": "Marketing Netpartners Limited",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "5/3/20",
    "Client First Project Date": "1/1/70",
    "Client First Quote Date": "5/8/17",
    "Client Last Quote Date": "2/19/20",
    "Address 1": "Geneva Place",
    "Country": "Virgin Islands (British) [VG]"
  },
  {
    "ID": "C000014",
    "Name": "AspireGlobal",
    "Legal Name [Official Company Name]": "AspireGlobal",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "1/16/19",
    "Client First Project Date": "5/17/17",
    "Client First Quote Date": "6/6/17",
    "Client Last Quote Date": "4/12/18",
    "Last Modification": "2019-11-08 16:27 EET",
    "Country": "Unknown [UNKNOWN]"
  },
  {
    "ID": "C000011",
    "Name": "Mico8",
    "Legal Name [Official Company Name]": "Mico 8 Ltd",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "11/5/18",
    "Client First Project Date": "9/28/17",
    "Client First Quote Date": "9/26/17",
    "Client Last Quote Date": "10/23/18",
    "Last Modification": "2018-11-09 16:39 EET",
    "Address 1": "B2 Industry Street",
    "City": "Qormi",
    "Country": "Malta [MT]",
    "Postal Code": "QRM 3000"
  },
  {
    "ID": "C000009",
    "Name": "Paragonex Dynamic",
    "Legal Name [Official Company Name]": "NGJ LIMITED",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "1/8/20",
    "Client First Project Date": "6/2/17",
    "Client First Quote Date": "6/21/17",
    "Client Last Quote Date": "1/7/20",
    "Address 1": "Willow House",
    "Country": "Isle of Man [IM]"
  },
  {
    "ID": "C000012",
    "Name": "Remax",
    "Legal Name [Official Company Name]": "X.N. United Property Brokers Ltd",
    "Industries": "Real Estate",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "6/18/19",
    "Client First Project Date": "8/9/17",
    "Client First Quote Date": "8/9/17",
    "Client Last Quote Date": "6/18/19",
    "Address 1": "46 Ayiou Athanasiou Avenue",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000005",
    "Name": "Trade360",
    "Legal Name [Official Company Name]": "MarketingMore LTD [Toyga]",
    "Industries": "Finance",
    "Account Manager": "Sakis Koulos",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "5/7/20",
    "Client First Project Date": "4/25/17",
    "Client First Quote Date": "4/25/17",
    "Client Last Quote Date": "5/7/20",
    "Address 1": "Akara Building",
    "Country": "Virgin Islands (British) [VG]"
  },
  {
    "ID": "C000017",
    "Name": "UFX.com",
    "Legal Name [Official Company Name]": "MarketingMore LTD [Toyga]",
    "Industries": "Finance",
    "Account Manager": "Sakis Koulos",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "5/7/20",
    "Client First Project Date": "4/19/17",
    "Client First Quote Date": "4/19/17",
    "Client Last Quote Date": "5/7/20",
    "Last Modification": "2020-02-28 10:22 EET",
    "Country": "Virgin Islands (British) [VG]"
  },
  {
    "ID": "C000007",
    "Name": "LottoSend",
    "Legal Name [Official Company Name]": "LottoSend",
    "Industries": "Lottery",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/31/17",
    "Client Last Project Date": "6/21/18",
    "Client First Project Date": "10/10/17",
    "Client First Quote Date": "10/10/17",
    "Client Last Quote Date": "6/19/18",
    "Last Modification": "2019-01-22 12:44 EET",
    "Country": "Unknown [UNKNOWN]"
  },
  {
    "ID": "C000022",
    "Name": "XTRF Test",
    "Legal Name [Official Company Name]": "XTRF Test",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "5/9/17",
    "Last Modification": "2017-05-09 18:43 EEST",
    "Country": "Poland [PL]"
  },
  {
    "ID": "C000024",
    "Name": "RovertMedia",
    "Legal Name [Official Company Name]": "RovertMedia",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/12/17",
    "Client Last Project Date": "5/16/17",
    "Client First Project Date": "5/16/17",
    "Client First Quote Date": "5/12/17",
    "Client Last Quote Date": "5/12/17",
    "Last Modification": "2018-11-22 08:52 EET",
    "Country": "United Kingdom [GB]"
  },
  {
    "ID": "C000026",
    "Name": "Seperia",
    "Legal Name [Official Company Name]": "Seperia",
    "Industries": "Marketing",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/25/17",
    "Client Last Project Date": "3/12/20",
    "Client First Project Date": "5/28/17",
    "Client First Quote Date": "5/25/17",
    "Client Last Quote Date": "4/6/20",
    "Last Modification": "2020-03-11 09:27 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000027",
    "Name": "Invertiscape Holdings LTD",
    "Legal Name [Official Company Name]": "Invertiscape Holdings LTD",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/26/17",
    "Client Last Project Date": "2/4/19",
    "Client First Project Date": "5/26/17",
    "Client First Quote Date": "5/26/17",
    "Client Last Quote Date": "2/4/19",
    "Last Modification": "2019-01-16 11:35 EET",
    "Address 1": "Mariella Paisanou Offices 102-103  365 Vashiotis Seafront 28th Octovriou str. Limassol Limassol 3107 Cyprus",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000030",
    "Name": "PSK",
    "Legal Name [Official Company Name]": "PSK",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/29/17",
    "Client Last Project Date": "6/2/17",
    "Client First Project Date": "5/31/17",
    "Last Modification": "2018-11-16 09:54 EET",
    "Country": "Croatia [HR]"
  },
  {
    "ID": "C000032",
    "Name": "OVERONIX TECHNOLOGIES LIMITED",
    "Legal Name [Official Company Name]": "OVERONIX TECHNOLOGIES LIMITED",
    "Industries": "Finance",
    "Account Manager": "Yara\tTytarenko",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "5/29/17",
    "Client Last Project Date": "4/7/20",
    "Client First Project Date": "5/30/17",
    "Client First Quote Date": "5/30/17",
    "Client Last Quote Date": "4/7/20",
    "Address 1": "Room 602",
    "Country": "Hong Kong [HK]"
  },
  {
    "ID": "C000033",
    "Name": "Pangea Localization Services",
    "Legal Name [Official Company Name]": "Pangea Localization Services",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "6/1/17",
    "Client Last Project Date": "4/27/20",
    "Client First Project Date": "6/1/17",
    "Client First Quote Date": "10/30/17",
    "Client Last Quote Date": "2/19/20",
    "Last Modification": "2019-06-10 15:28 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000035",
    "Name": "HeySpin",
    "Legal Name [Official Company Name]": "HeySpin",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "6/6/17",
    "Client Last Project Date": "6/8/17",
    "Client First Project Date": "6/6/17",
    "Client First Quote Date": "6/6/17",
    "Client Last Quote Date": "6/6/17",
    "Last Modification": "2018-10-17 08:48 EEST"
  },
  {
    "ID": "C000036",
    "Name": "David Malits Public Relations",
    "Legal Name [Official Company Name]": "David Malits Public Relations",
    "Industries": "Marketing",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "6/15/17",
    "Client Last Project Date": "11/20/18",
    "Client First Project Date": "6/15/17",
    "Client First Quote Date": "7/4/17",
    "Client Last Quote Date": "11/19/18",
    "Last Modification": "2018-12-05 15:54 EET"
  },
  {
    "ID": "C000040",
    "Name": "Richfield Capital Ltd",
    "Legal Name [Official Company Name]": "Richfield Capital Ltd",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "6/29/17",
    "Client Last Project Date": "6/29/17",
    "Client First Project Date": "6/29/17",
    "Address 1": "No. 5 Cork Street",
    "Country": "Belize [BZ]"
  },
  {
    "ID": "C000042",
    "Name": "ForexValley Tech Ltd",
    "Legal Name [Official Company Name]": "ForexValley Tech Ltd",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "7/7/17",
    "Client Last Project Date": "9/3/18",
    "Client First Project Date": "7/19/17",
    "Client First Quote Date": "7/7/17",
    "Client Last Quote Date": "8/27/18",
    "Last Modification": "2018-11-16 08:36 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000043",
    "Name": "Recognia",
    "Legal Name [Official Company Name]": "Recognia",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "7/12/17",
    "Client Last Project Date": "12/21/17",
    "Client First Project Date": "10/18/17",
    "Client First Quote Date": "7/12/17",
    "Client Last Quote Date": "12/19/17",
    "Last Modification": "2018-11-16 07:29 EET",
    "City": "Ottawa",
    "Country": "Canada [CA]"
  },
  {
    "ID": "C000046",
    "Name": "Soft2Bet",
    "Legal Name [Official Company Name]": "Soft2Bet",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "AAC 2017",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "7/20/17",
    "Client Last Project Date": "4/10/20",
    "Client First Project Date": "7/20/17",
    "Client First Quote Date": "7/20/17",
    "Client Last Quote Date": "4/20/20",
    "Last Modification": "2020-03-06 10:26 EET"
  },
  {
    "ID": "C000048",
    "Name": "bnology",
    "Legal Name [Official Company Name]": "bnology",
    "Industries": "Finance",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "7/27/17",
    "Client Last Project Date": "5/5/20",
    "Client First Project Date": "7/27/17",
    "Client First Quote Date": "7/27/17",
    "Client Last Quote Date": "5/5/20",
    "Last Modification": "2020-03-31 10:19 EEST"
  },
  {
    "ID": "C000049",
    "Name": "Linkfluence",
    "Legal Name [Official Company Name]": "Linkfluence",
    "Industries": "Other",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "8/2/17",
    "Client Last Project Date": "1/9/18",
    "Client First Project Date": "8/3/17",
    "Client First Quote Date": "8/2/17",
    "Client Last Quote Date": "1/5/18",
    "Last Modification": "2018-11-22 08:54 EET"
  },
  {
    "ID": "C000050",
    "Name": "JMfinancial",
    "Legal Name [Official Company Name]": "JMfinancial",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "8/4/17",
    "Client Last Project Date": "8/26/18",
    "Client First Project Date": "9/13/17",
    "Client First Quote Date": "8/4/17",
    "Client Last Quote Date": "7/16/18",
    "Last Modification": "2018-12-10 15:48 EET"
  },
  {
    "ID": "C000052",
    "Name": "Pangea Translation Services",
    "Legal Name [Official Company Name]": "Pangea Translation Services",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Website",
    "First Contact Date2": "8/14/17",
    "Client Last Project Date": "4/21/20",
    "Client First Project Date": "3/22/18",
    "Client First Quote Date": "8/14/17",
    "Client Last Quote Date": "9/18/19",
    "Last Modification": "2019-06-27 14:25 EEST"
  },
  {
    "ID": "C000057",
    "Name": "EVERFX",
    "Legal Name [Official Company Name]": "EVERFX",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "9/25/17",
    "Client Last Project Date": "12/9/19",
    "Client First Project Date": "12/5/17",
    "Client First Quote Date": "12/4/17",
    "Client Last Quote Date": "12/9/19",
    "Last Modification": "2019-12-09 16:08 EET"
  },
  {
    "ID": "C000061",
    "Name": "24option",
    "Legal Name [Official Company Name]": "Richfield (24option)",
    "Industries": "Forex",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "10/5/17",
    "Client Last Project Date": "4/8/20",
    "Client First Project Date": "10/9/17",
    "Client First Quote Date": "10/5/17",
    "Client Last Quote Date": "4/8/20",
    "Last Modification": "2020-04-06 17:10 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000068",
    "Name": "Playngo",
    "Legal Name [Official Company Name]": "Playngo",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "10/16/17",
    "Client Last Project Date": "3/23/20",
    "Client First Project Date": "10/16/17",
    "Client First Quote Date": "10/16/17",
    "Client Last Quote Date": "3/23/20",
    "Address 1": "87B",
    "Country": "Malta [MT]"
  },
  {
    "ID": "C000069",
    "Name": "RW Markets",
    "Legal Name [Official Company Name]": "MarketingMore LTD [Toyga]",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "10/17/17",
    "Client Last Project Date": "7/11/19",
    "Client First Project Date": "10/23/17",
    "Client First Quote Date": "10/23/17",
    "Client Last Quote Date": "7/11/19",
    "Last Modification": "2019-06-27 15:23 EEST"
  },
  {
    "ID": "C000085",
    "Name": "TEST_API_XTRF",
    "Legal Name [Official Company Name]": "TEST_API_XTRF",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "12/1/17",
    "Client Last Project Date": "2/13/18",
    "Client First Project Date": "12/1/17",
    "Client First Quote Date": "12/1/17",
    "Client Last Quote Date": "2/13/18",
    "Last Modification": "2018-01-04 15:18 EET",
    "Country": "Poland [PL]"
  },
  {
    "ID": "C000086",
    "Name": "Playtika",
    "Legal Name [Official Company Name]": "Playtika",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "12/4/17",
    "Client Last Project Date": "5/4/20",
    "Client First Project Date": "12/5/17",
    "Client First Quote Date": "12/4/17",
    "Client Last Quote Date": "5/4/20",
    "Last Modification": "2020-03-06 10:17 EET"
  },
  {
    "ID": "C000098",
    "Name": "Wargaming",
    "Legal Name [Official Company Name]": "Wargaming",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/1/18",
    "Client Last Project Date": "2/13/18",
    "Client First Project Date": "2/1/18",
    "Client First Quote Date": "2/1/18",
    "Client Last Quote Date": "10/4/19",
    "Last Modification": "2019-10-04 11:31 EEST"
  },
  {
    "ID": "C000105",
    "Name": "CoolCousin",
    "Legal Name [Official Company Name]": "CoolCousin",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/15/18",
    "Client Last Project Date": "1/15/19",
    "Client First Project Date": "2/15/18",
    "Client First Quote Date": "2/15/18",
    "Client Last Quote Date": "1/15/19",
    "Last Modification": "2020-01-22 14:29 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000109",
    "Name": "Envionex",
    "Legal Name [Official Company Name]": "Envionex",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2018",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/23/18",
    "Last Modification": "2019-06-21 17:30 EEST"
  },
  {
    "ID": "C000117",
    "Name": "PSGM Tech",
    "Legal Name [Official Company Name]": "GUM LTD",
    "Industries": "ICO",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2018",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/5/18",
    "Client Last Project Date": "6/24/19",
    "Client First Project Date": "3/5/18",
    "Client First Quote Date": "3/5/18",
    "Client Last Quote Date": "6/24/19",
    "Last Modification": "2020-04-27 11:15 EEST",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000116",
    "Name": "1Market",
    "Legal Name [Official Company Name]": "MarketingMore LTD [Toyga]",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "3/5/18",
    "Client Last Project Date": "6/13/19",
    "Client First Project Date": "3/5/18",
    "Client First Quote Date": "3/5/18",
    "Client Last Quote Date": "6/13/19",
    "Last Modification": "2020-02-28 10:23 EET"
  },
  {
    "ID": "C000126",
    "Name": "MrPlayPartner",
    "Legal Name [Official Company Name]": "MARKETPLAY LTD",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "ICE/LAC 2018",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "3/22/18",
    "Client Last Project Date": "5/4/20",
    "Client First Project Date": "3/22/18",
    "Client First Quote Date": "3/22/18",
    "Client Last Quote Date": "4/21/20",
    "Address 1": "Level G",
    "Country": "Malta [MT]"
  },
  {
    "ID": "C000127",
    "Name": "Casino Technology",
    "Legal Name [Official Company Name]": "Casino Technology",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2018",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/22/18",
    "Client Last Project Date": "11/25/19",
    "Client First Project Date": "3/24/18",
    "Client First Quote Date": "3/22/18",
    "Client Last Quote Date": "11/25/19",
    "Last Modification": "2019-10-03 15:41 EEST",
    "Country": "Bulgaria [BG]"
  },
  {
    "ID": "C000142",
    "Name": "Pepperstone",
    "Legal Name [Official Company Name]": "Pepperstone",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "4/11/18",
    "Client Last Project Date": "5/7/20",
    "Client First Project Date": "4/12/18",
    "Client First Quote Date": "4/11/18",
    "Client Last Quote Date": "5/6/20",
    "Last Modification": "2020-04-29 12:03 EEST"
  },
  {
    "ID": "C000141",
    "Name": "Almahfaza",
    "Legal Name [Official Company Name]": "MarketingMore LTD [Toyga]",
    "Account Manager": "Sakis Koulos",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "4/11/18",
    "Client Last Project Date": "8/12/19",
    "Client First Project Date": "4/11/18",
    "Client First Quote Date": "4/11/18",
    "Client Last Quote Date": "7/15/19",
    "Last Modification": "2020-01-28 10:21 EET"
  },
  {
    "ID": "C000311",
    "Name": "Client-name",
    "Legal Name [Official Company Name]": "Test-client-name",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "4/17/18",
    "Client Last Project Date": "6/14/18",
    "Client First Project Date": "7/30/15",
    "Client First Quote Date": "4/20/18",
    "Client Last Quote Date": "6/5/18",
    "Last Modification": "2018-06-05 11:38 EEST",
    "Country": "Russia [RU]"
  },
  {
    "ID": "C000367",
    "Name": "GreySnowPoker",
    "Legal Name [Official Company Name]": "GreySnowPoker",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "5/10/18",
    "Client Last Project Date": "4/22/20",
    "Client First Project Date": "5/21/18",
    "Client First Quote Date": "5/21/18",
    "Client Last Quote Date": "4/22/20",
    "Last Modification": "2020-03-06 10:21 EET"
  },
  {
    "ID": "C000388",
    "Name": "Sweetch",
    "Legal Name [Official Company Name]": "Sweetch",
    "Industries": "Health Care",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/24/18",
    "Client Last Project Date": "2/10/20",
    "Client First Project Date": "7/5/19",
    "Client First Quote Date": "7/5/19",
    "Client Last Quote Date": "11/19/19",
    "Last Modification": "2019-11-19 15:17 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000409",
    "Name": "1xBet",
    "Legal Name [Official Company Name]": "1xBet",
    "Industries": "Sports & Recreation",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "BAC 2017",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "6/13/18",
    "Client Last Project Date": "3/6/19",
    "Client First Project Date": "6/13/18",
    "Client First Quote Date": "3/6/19",
    "Client Last Quote Date": "3/6/19",
    "Last Modification": "2019-03-06 11:28 EET",
    "Country": "Russia [RU]"
  },
  {
    "ID": "C000414",
    "Name": "Native",
    "Legal Name [Official Company Name]": "Charlie Curran",
    "Industries": "Marketing Agency",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "6/25/18",
    "Client Last Project Date": "12/7/18",
    "Client First Project Date": "9/13/18",
    "Client First Quote Date": "9/13/18",
    "Client Last Quote Date": "12/7/18",
    "Last Modification": "2019-06-21 17:39 EEST",
    "Country": "Unknown [UNKNOWN]"
  },
  {
    "ID": "C000425",
    "Name": "PlugIt",
    "Legal Name [Official Company Name]": "PlugIt",
    "Industries": "Market Research",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "iFX 2018",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "7/13/18",
    "Client Last Project Date": "5/4/20",
    "Client First Project Date": "7/13/18",
    "Client First Quote Date": "10/18/18",
    "Client Last Quote Date": "5/1/20",
    "Last Modification": "2020-05-04 16:12 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000430",
    "Name": "Airsource",
    "Legal Name [Official Company Name]": "Airsource Ltd",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "7/31/18",
    "Client Last Project Date": "4/16/20",
    "Client First Project Date": "7/31/18",
    "Client First Quote Date": "7/31/18",
    "Client Last Quote Date": "4/15/20",
    "Last Modification": "2020-04-16 17:16 EEST"
  },
  {
    "ID": "C000441",
    "Name": "Brokeree Solutions",
    "Legal Name [Official Company Name]": "Brokeree Solutions",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "iFX 2018",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "8/27/18",
    "Client Last Project Date": "9/7/18",
    "Client First Project Date": "8/27/18",
    "Client First Quote Date": "8/27/18",
    "Client Last Quote Date": "8/27/18",
    "Last Modification": "2019-06-21 17:47 EEST"
  },
  {
    "ID": "C000447",
    "Name": "Action Digital Agency",
    "Legal Name [Official Company Name]": "Action Digital Agency",
    "Industries": "Marketing Agency",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Cold call",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "9/13/18",
    "Client Last Project Date": "2/19/19",
    "Client First Project Date": "2/5/19",
    "Client First Quote Date": "1/25/19",
    "Client Last Quote Date": "1/25/19",
    "Last Modification": "2019-06-21 17:47 EEST"
  },
  {
    "ID": "C000448",
    "Name": "Translators Without Borders",
    "Legal Name [Official Company Name]": "Translators Without Borders",
    "Industries": "Nonprofit",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "9/18/18",
    "Client Last Project Date": "3/12/20",
    "Client First Project Date": "9/18/18",
    "Last Modification": "2018-09-18 12:02 EEST"
  },
  {
    "ID": "C000452",
    "Name": "HighFX",
    "Legal Name [Official Company Name]": "HighFX",
    "Account Manager": "Sakis Koulos",
    "First Contact Date2": "9/26/18",
    "Client Last Project Date": "12/22/18",
    "Client First Project Date": "9/27/18",
    "Client First Quote Date": "9/26/18",
    "Client Last Quote Date": "12/20/18",
    "Last Modification": "2018-09-27 07:53 EEST"
  },
  {
    "ID": "C000455",
    "Name": "Affidelity ( Irene - Jambo &Neptune)",
    "Legal Name [Official Company Name]": "Affidelity",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "10/8/18",
    "Client Last Project Date": "4/8/20",
    "Client First Project Date": "10/8/18",
    "Client First Quote Date": "10/10/18",
    "Client Last Quote Date": "4/8/20",
    "Last Modification": "2019-11-25 14:09 EET",
    "Address 1": "12 Egoz street",
    "City": "Holon",
    "Country": "Israel [IL]",
    "Postal Code": "5850911"
  },
  {
    "ID": "C000456",
    "Name": "Iforium",
    "Legal Name [Official Company Name]": "Iforium",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/9/18",
    "Client Last Project Date": "6/13/19",
    "Client First Project Date": "10/10/18",
    "Client First Quote Date": "10/9/18",
    "Client Last Quote Date": "6/12/19",
    "Last Modification": "2019-06-21 17:41 EEST",
    "Country": "United Kingdom [GB]"
  },
  {
    "ID": "C000458",
    "Name": "G4 Shift Services LTD",
    "Legal Name [Official Company Name]": "G4 Shift Services LTD",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "10/15/18",
    "Client Last Project Date": "5/4/20",
    "Client First Project Date": "10/22/18",
    "Client First Quote Date": "10/15/18",
    "Client Last Quote Date": "5/4/20",
    "Last Modification": "2020-01-31 09:49 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000460",
    "Name": "ForexFS",
    "Legal Name [Official Company Name]": "ForexFS",
    "Industries": "Forex",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "10/18/18",
    "Client Last Project Date": "4/2/20",
    "Client First Project Date": "10/18/18",
    "Client First Quote Date": "2/7/19",
    "Client Last Quote Date": "4/2/20",
    "Last Modification": "2020-03-06 10:19 EET",
    "Country": "Australia [AU]"
  },
  {
    "ID": "C000483",
    "Name": "BITSME",
    "Legal Name [Official Company Name]": "BITSME",
    "Industries": "ICO",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "First Contact Date2": "10/25/18",
    "Client Last Project Date": "12/4/18",
    "Client First Project Date": "10/30/18",
    "Client First Quote Date": "10/30/18",
    "Client Last Quote Date": "12/1/18",
    "Last Modification": "2018-12-21 09:09 EET"
  },
  {
    "ID": "C000511",
    "Name": "KC Firiakis Services LTD",
    "Legal Name [Official Company Name]": "KC Firiakis Services LTD",
    "Industries": "Law",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/30/18",
    "Client Last Project Date": "2/17/20",
    "Client First Project Date": "10/30/18",
    "Client First Quote Date": "11/1/18",
    "Client Last Quote Date": "2/18/20",
    "Last Modification": "2019-08-28 10:36 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000513",
    "Name": "IFX Expo",
    "Legal Name [Official Company Name]": "IFX Expo",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/1/18",
    "Client Last Project Date": "12/17/18",
    "Client First Project Date": "11/6/18",
    "Client First Quote Date": "11/1/18",
    "Client Last Quote Date": "12/14/18",
    "Last Modification": "2018-12-14 11:31 EET"
  },
  {
    "ID": "C000517",
    "Name": "Innovaventis",
    "Legal Name [Official Company Name]": "Innovaventis",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "AAC 2018",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/9/18",
    "Client Last Project Date": "4/25/19",
    "Client First Project Date": "11/14/18",
    "Client First Quote Date": "11/9/18",
    "Client Last Quote Date": "4/24/19",
    "Last Modification": "2019-05-06 16:36 EEST"
  },
  {
    "ID": "C000518",
    "Name": "Maximos",
    "Legal Name [Official Company Name]": "Maximos",
    "Industries": "Architecture & Design",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/13/18",
    "Client Last Project Date": "11/22/18",
    "Client First Project Date": "11/21/18",
    "Client First Quote Date": "11/13/18",
    "Client Last Quote Date": "11/13/18",
    "Last Modification": "2018-11-13 13:21 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000523",
    "Name": "KERABELLE CONSULTANTS LTD",
    "Legal Name [Official Company Name]": "KERABELLE CONSULTANTS LTD",
    "Industries": "Consulting",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/26/18",
    "Client Last Project Date": "6/24/19",
    "Client First Project Date": "11/26/18",
    "Client First Quote Date": "11/26/18",
    "Client Last Quote Date": "6/24/19",
    "Last Modification": "2019-06-28 10:07 EEST"
  },
  {
    "ID": "C000526",
    "Name": "Betinvest",
    "Legal Name [Official Company Name]": "Betinvest",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/29/18",
    "Client Last Project Date": "11/29/18",
    "Client First Project Date": "11/29/18",
    "Last Modification": "2018-12-05 15:32 EET"
  },
  {
    "ID": "C000535",
    "Name": "CODERE",
    "Legal Name [Official Company Name]": "CODERE",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "12/20/18",
    "Client Last Project Date": "5/7/20",
    "Client First Project Date": "12/27/18",
    "Client First Quote Date": "12/27/18",
    "Client Last Quote Date": "5/7/20",
    "Last Modification": "2020-03-06 10:24 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000558",
    "Name": "OneTouch",
    "Legal Name [Official Company Name]": "OneTouch",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2019",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/12/19",
    "Client Last Project Date": "3/26/19",
    "Client First Project Date": "2/13/19",
    "Client First Quote Date": "2/12/19",
    "Client Last Quote Date": "3/26/19",
    "Last Modification": "2019-06-21 17:35 EEST",
    "Country": "Estonia [EE]"
  },
  {
    "ID": "C000560",
    "Name": "Casavi",
    "Legal Name [Official Company Name]": "Casavi",
    "Industries": "Real Estate",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/14/19",
    "Client Last Project Date": "3/13/19",
    "Client First Project Date": "3/1/19",
    "Client First Quote Date": "2/14/19",
    "Client Last Quote Date": "2/21/19",
    "Last Modification": "2019-06-21 17:45 EEST",
    "Country": "Germany [DE]"
  },
  {
    "ID": "C000562",
    "Name": "Andreas Konnaris LLC",
    "Legal Name [Official Company Name]": "Andreas Konnaris LLC",
    "Industries": "Law",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/20/19",
    "Client Last Project Date": "2/20/19",
    "Client First Project Date": "2/20/19",
    "Client First Quote Date": "2/20/19",
    "Client Last Quote Date": "2/20/19",
    "Last Modification": "2019-06-21 17:36 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000563",
    "Name": "Ezugi",
    "Legal Name [Official Company Name]": "Ezugi",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2019",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/21/19",
    "Client Last Project Date": "3/30/19",
    "Client First Project Date": "2/24/19",
    "Client First Quote Date": "2/21/19",
    "Client Last Quote Date": "3/26/19",
    "Last Modification": "2019-06-21 17:35 EEST"
  },
  {
    "ID": "C000564",
    "Name": "Zariba",
    "Legal Name [Official Company Name]": "Zariba",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2019",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/22/19",
    "Client Last Project Date": "2/28/19",
    "Client First Project Date": "2/25/19",
    "Client First Quote Date": "2/25/19",
    "Client Last Quote Date": "2/25/19",
    "Last Modification": "2019-06-21 17:47 EEST",
    "Country": "Bulgaria [BG]"
  },
  {
    "ID": "C000566",
    "Name": "The Soul Publishing",
    "Legal Name [Official Company Name]": "The Soul Publishing",
    "Industries": "Other",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/28/19",
    "Client Last Project Date": "8/16/19",
    "Client First Project Date": "3/4/19",
    "Client First Quote Date": "2/28/19",
    "Client Last Quote Date": "8/16/19",
    "Last Modification": "2019-08-19 17:44 EEST"
  },
  {
    "ID": "C000574",
    "Name": "nextmarkets Trading Limited",
    "Legal Name [Official Company Name]": "nextmarkets Trading Limited",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "3/14/19",
    "Client Last Project Date": "12/20/19",
    "Client First Project Date": "3/15/19",
    "Client First Quote Date": "3/29/19",
    "Client Last Quote Date": "12/20/19",
    "Last Modification": "2019-06-28 14:40 EEST",
    "Country": "Malta [MT]"
  },
  {
    "ID": "C000575",
    "Name": "Ganapati",
    "Legal Name [Official Company Name]": "Ganapati",
    "Industries": "ICO",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "Sigma 2018",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/22/19",
    "Client Last Project Date": "2/5/20",
    "Client First Project Date": "4/1/19",
    "Client First Quote Date": "3/22/19",
    "Client Last Quote Date": "2/5/20",
    "Last Modification": "2020-03-06 10:25 EET",
    "Country": "Japan [JP]"
  },
  {
    "ID": "C000576",
    "Name": "Promo",
    "Legal Name [Official Company Name]": "Promo",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/26/19",
    "Client Last Project Date": "3/29/19",
    "Client First Project Date": "3/26/19",
    "Client First Quote Date": "3/26/19",
    "Client Last Quote Date": "3/29/19",
    "Last Modification": "2019-03-26 11:10 EET"
  },
  {
    "ID": "C000583",
    "Name": "Davina",
    "Legal Name [Official Company Name]": "Johnson",
    "Industries": "Other",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "4/19/19",
    "Client Last Project Date": "4/19/19",
    "Client First Project Date": "4/19/19",
    "Client First Quote Date": "4/19/19",
    "Client Last Quote Date": "4/19/19",
    "Last Modification": "2020-02-25 15:19 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000586",
    "Name": "Etsy",
    "Legal Name [Official Company Name]": "Etsy",
    "Industries": "E-commerce",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/8/19",
    "Client Last Project Date": "5/14/19",
    "Client First Project Date": "5/14/19",
    "Client First Quote Date": "5/8/19",
    "Client Last Quote Date": "5/8/19",
    "Last Modification": "2019-06-21 17:44 EEST",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000587",
    "Name": "XM Forex",
    "Legal Name [Official Company Name]": "XM Forex",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/9/19",
    "Client Last Project Date": "2/13/20",
    "Client First Project Date": "5/9/19",
    "Client First Quote Date": "5/9/19",
    "Client Last Quote Date": "2/13/20",
    "Last Modification": "2019-06-21 17:39 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000589",
    "Name": "Richard Wanigasekera",
    "Legal Name [Official Company Name]": "Richard Wanigasekera",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2019",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/17/19",
    "Client Last Project Date": "5/17/19",
    "Client First Project Date": "5/17/19",
    "Client First Quote Date": "5/17/19",
    "Client Last Quote Date": "5/17/19",
    "Last Modification": "2019-05-17 15:42 EEST",
    "Country": "United Kingdom [GB]"
  },
  {
    "ID": "C000591",
    "Name": "Queensway Academy",
    "Legal Name [Official Company Name]": "MarketingMore LTD [Toyga]",
    "Account Manager": "Sakis Koulos",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "5/21/19",
    "Client Last Project Date": "4/30/20",
    "Client First Project Date": "5/27/19",
    "Client First Quote Date": "5/27/19",
    "Client Last Quote Date": "4/30/20",
    "Last Modification": "2020-03-25 13:46 EET"
  },
  {
    "ID": "C000594",
    "Name": "Play Logia N.V.",
    "Legal Name [Official Company Name]": "Play Logia N.V.",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "5/28/19",
    "Client Last Project Date": "5/6/20",
    "Client First Project Date": "5/28/19",
    "Client First Quote Date": "5/28/19",
    "Client Last Quote Date": "5/6/20",
    "Last Modification": "2020-04-29 09:25 EEST",
    "Address 1": "P.O.Box 6248",
    "City": "Curacao"
  },
  {
    "ID": "C000595",
    "Name": "FAI Comply",
    "Legal Name [Official Company Name]": "FAI Comply",
    "Industries": "Forex",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/28/19",
    "Client Last Project Date": "5/5/20",
    "Client First Project Date": "5/28/19",
    "Client First Quote Date": "5/28/19",
    "Client Last Quote Date": "5/5/20",
    "Last Modification": "2020-05-05 15:34 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000600",
    "Name": "Octa Markets",
    "Legal Name [Official Company Name]": "Octa Markets",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "6/24/19",
    "Client Last Project Date": "4/6/20",
    "Client First Project Date": "6/24/19",
    "Client First Quote Date": "6/24/19",
    "Client Last Quote Date": "4/6/20",
    "Last Modification": "2019-09-16 17:22 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000604",
    "Name": "Fantasma Games",
    "Legal Name [Official Company Name]": "Fantasma Games",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "LinkedIn",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "7/1/19",
    "Client Last Project Date": "3/16/20",
    "Client First Project Date": "7/3/19",
    "Client First Quote Date": "7/2/19",
    "Client Last Quote Date": "3/16/20",
    "Last Modification": "2020-05-08 16:16 EEST"
  },
  {
    "ID": "C000606",
    "Name": "Funfair Technologies",
    "Legal Name [Official Company Name]": "Funfair Technologies",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2019",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "7/4/19",
    "Client Last Project Date": "2/21/20",
    "Client First Project Date": "7/4/19",
    "Client First Quote Date": "7/4/19",
    "Client Last Quote Date": "2/21/20",
    "Last Modification": "2020-02-14 17:35 EET"
  },
  {
    "ID": "C000607",
    "Name": "Delorbis",
    "Legal Name [Official Company Name]": "Delorbis",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "7/8/19",
    "Client Last Project Date": "7/8/19",
    "Client First Project Date": "7/8/19",
    "Client First Quote Date": "7/8/19",
    "Client Last Quote Date": "7/8/19",
    "Last Modification": "2019-07-08 14:27 EEST"
  },
  {
    "ID": "C000608",
    "Name": "Casino Intense",
    "Legal Name [Official Company Name]": "Sterinvest Se",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2019",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "7/9/19",
    "Client Last Project Date": "12/19/19",
    "Client First Project Date": "7/12/19",
    "Client First Quote Date": "7/12/19",
    "Client Last Quote Date": "12/19/19",
    "Last Modification": "2019-07-16 15:06 EEST"
  },
  {
    "ID": "C000614",
    "Name": "Alvexo",
    "Legal Name [Official Company Name]": "VPR Safe Financial Group Ltd",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "7/22/19",
    "Client Last Project Date": "11/5/19",
    "Client First Project Date": "7/22/19",
    "Client First Quote Date": "7/22/19",
    "Client Last Quote Date": "11/5/19",
    "Address 1": "1",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000615",
    "Name": "Oxy Health Europe",
    "Legal Name [Official Company Name]": "Oxy Health Europe",
    "Industries": "Pharma",
    "Account Manager": "Angelica Nicolaou",
    "First Contact Date2": "7/23/19",
    "Client First Quote Date": "7/23/19",
    "Client Last Quote Date": "7/23/19",
    "Last Modification": "2019-07-23 15:16 EEST",
    "Country": "Spain [ES]"
  },
  {
    "ID": "C000617",
    "Name": "Betgames.tv",
    "Legal Name [Official Company Name]": "Betgames.tv",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "7/24/19",
    "Client Last Project Date": "5/4/20",
    "Client First Project Date": "8/5/19",
    "Client First Quote Date": "8/5/19",
    "Client Last Quote Date": "5/4/20",
    "Last Modification": "2020-03-06 10:23 EET",
    "Country": "Lithuania [LT]"
  },
  {
    "ID": "C000619",
    "Name": "Maria Malai",
    "Legal Name [Official Company Name]": "Maria Malai",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "7/29/19",
    "Client Last Project Date": "7/29/19",
    "Client First Project Date": "7/29/19",
    "Client First Quote Date": "7/29/19",
    "Client Last Quote Date": "7/29/19",
    "Last Modification": "2019-07-29 12:21 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000621",
    "Name": "Inplay Matrix Limited",
    "Legal Name [Official Company Name]": "Inplay Matrix Limited",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "8/1/19",
    "Last Modification": "2019-08-01 10:54 EEST"
  },
  {
    "ID": "C000623",
    "Name": "Bet2U",
    "Legal Name [Official Company Name]": "Bet2U",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Trade show",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "8/2/19",
    "Client Last Project Date": "9/30/19",
    "Client First Project Date": "9/30/19",
    "Client First Quote Date": "8/2/19",
    "Client Last Quote Date": "10/28/19",
    "Last Modification": "2019-08-02 13:12 EEST"
  },
  {
    "ID": "C000626",
    "Name": "NetGaming",
    "Legal Name [Official Company Name]": "NG Entertainment LTD",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "ICE/LAC 2019",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "8/12/19",
    "Client Last Project Date": "9/10/19",
    "Client First Project Date": "9/2/19",
    "Client First Quote Date": "9/4/19",
    "Client Last Quote Date": "4/24/20",
    "Address 1": "- 97 Windsor st.",
    "Country": "Malta [MT]"
  },
  {
    "ID": "C000633",
    "Name": "Individuals",
    "Legal Name [Official Company Name]": "Individuals",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "9/9/19",
    "Client Last Project Date": "2/21/20",
    "Client First Project Date": "9/9/19",
    "Client First Quote Date": "9/9/19",
    "Client Last Quote Date": "2/21/20",
    "Last Modification": "2019-10-29 10:50 EET"
  },
  {
    "ID": "C000635",
    "Name": "DYISY LTD",
    "Legal Name [Official Company Name]": "DYISY LTD",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "9/23/19",
    "Client Last Project Date": "11/20/19",
    "Client First Project Date": "9/23/19",
    "Client First Quote Date": "9/23/19",
    "Client Last Quote Date": "11/20/19",
    "Last Modification": "2019-11-20 17:41 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000637",
    "Name": "PRAGMATICPLAY SRL",
    "Legal Name [Official Company Name]": "PRAGMATICPLAY SRL",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "9/26/19",
    "Client Last Project Date": "4/23/20",
    "Client First Project Date": "10/4/19",
    "Client First Quote Date": "10/3/19",
    "Client Last Quote Date": "5/5/20",
    "Last Modification": "2020-05-05 16:38 EEST",
    "Country": "Romania [RO]"
  },
  {
    "ID": "C000638",
    "Name": "FXStreet",
    "Legal Name [Official Company Name]": "FXStreet",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/2/19",
    "Client First Quote Date": "10/2/19",
    "Client Last Quote Date": "10/2/19",
    "Last Modification": "2019-10-02 13:55 EEST"
  },
  {
    "ID": "C000639",
    "Name": "Stepico",
    "Legal Name [Official Company Name]": "Stepico",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "LinkedIn",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "10/2/19",
    "Client Last Project Date": "3/6/20",
    "Client First Project Date": "10/3/19",
    "Client First Quote Date": "10/2/19",
    "Client Last Quote Date": "3/6/20",
    "Last Modification": "2020-03-26 15:50 EET"
  },
  {
    "ID": "C000640",
    "Name": "A-CLID Ltd",
    "Legal Name [Official Company Name]": "A-CLID Ltd",
    "Industries": "Consulting",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Pre-payment",
    "First Contact Date2": "10/3/19",
    "Client Last Project Date": "10/21/19",
    "Client First Project Date": "10/14/19",
    "Client First Quote Date": "10/3/19",
    "Client Last Quote Date": "10/21/19",
    "Last Modification": "2019-11-08 16:10 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000643",
    "Name": "LGC Properties buy the Sea LTD",
    "Legal Name [Official Company Name]": "LGC Properties buy the Sea LTD",
    "Industries": "Real Estate",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/14/19",
    "Client Last Project Date": "11/5/19",
    "Client First Project Date": "10/29/19",
    "Client First Quote Date": "10/29/19",
    "Client Last Quote Date": "11/4/19",
    "Last Modification": "2019-11-04 11:00 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000644",
    "Name": "CEDEM AG",
    "Legal Name [Official Company Name]": "CEDEM AG",
    "Industries": "Pharma",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "LinkedIn",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/16/19",
    "Client First Quote Date": "10/16/19",
    "Client Last Quote Date": "10/16/19",
    "Last Modification": "2020-03-30 14:05 EEST",
    "Address 1": "Bergstrasse 107",
    "City": "ZÃ¼rich",
    "Country": "Switzerland [CH]",
    "Postal Code": "8032"
  },
  {
    "ID": "C000645",
    "Name": "Zordix",
    "Legal Name [Official Company Name]": "Zordix",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/21/19",
    "Client Last Project Date": "1/8/20",
    "Client First Project Date": "10/22/19",
    "Client First Quote Date": "10/21/19",
    "Client Last Quote Date": "1/8/20",
    "Last Modification": "2019-10-21 16:35 EEST"
  },
  {
    "ID": "C000646",
    "Name": "AsiaBet",
    "Legal Name [Official Company Name]": "AsiaBet",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/23/19",
    "Client First Quote Date": "10/24/19",
    "Client Last Quote Date": "11/21/19",
    "Last Modification": "2019-11-21 09:57 EET",
    "Country": "Malta [MT]"
  },
  {
    "ID": "C000647",
    "Name": "SoftSwiss",
    "Legal Name [Official Company Name]": "N.V. Direx",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "10/30/19",
    "Client Last Project Date": "2/19/20",
    "Client First Project Date": "12/6/19",
    "Client First Quote Date": "10/30/19",
    "Client Last Quote Date": "2/18/20",
    "Last Modification": "2020-02-19 10:20 EET"
  },
  {
    "ID": "C000651",
    "Name": "Koineks",
    "Legal Name [Official Company Name]": "Koineks",
    "Industries": "ICO",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/4/19",
    "Last Modification": "2019-11-04 14:39 EET",
    "Country": "Turkey [TR]"
  },
  {
    "ID": "C000654",
    "Name": "Metaswitch Networks",
    "Legal Name [Official Company Name]": "Metaswitch Networks",
    "Industries": "Marketing Agency",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/4/19",
    "Last Modification": "2019-11-04 16:56 EET",
    "Country": "United Kingdom [GB]"
  },
  {
    "ID": "C000655",
    "Name": "XB Prime",
    "Legal Name [Official Company Name]": "XB Prime",
    "Industries": "Forex",
    "Account Manager": "Amarita Sohal",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/8/19",
    "Client Last Project Date": "5/5/20",
    "Client First Project Date": "2/27/20",
    "Client First Quote Date": "11/8/19",
    "Client Last Quote Date": "5/5/20",
    "Last Modification": "2020-02-28 16:16 EET",
    "Address 1": "PSMH LTD.  Spyrou Kyprianou 67",
    "City": "Limassol",
    "Country": "Cyprus [CY]",
    "Postal Code": "4042"
  },
  {
    "ID": "C000656",
    "Name": "Rewire",
    "Legal Name [Official Company Name]": "Rewire",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Partner referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/12/19",
    "Client Last Project Date": "2/12/20",
    "Client First Project Date": "2/3/20",
    "Client First Quote Date": "11/12/19",
    "Client Last Quote Date": "2/12/20",
    "Last Modification": "2019-11-12 15:46 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000658",
    "Name": "Amrut software",
    "Legal Name [Official Company Name]": "Amrut software",
    "Industries": "E-commerce",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Gitex 2019",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/25/19",
    "Client First Quote Date": "11/25/19",
    "Client Last Quote Date": "11/25/19",
    "Last Modification": "2019-11-25 14:45 EET",
    "Country": "India [IN]"
  },
  {
    "ID": "C000657",
    "Name": "Alderon",
    "Legal Name [Official Company Name]": "Alderon",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/25/19",
    "Client First Quote Date": "11/25/19",
    "Client Last Quote Date": "11/25/19",
    "Last Modification": "2019-11-25 14:13 EET",
    "Country": "Canada [CA]"
  },
  {
    "ID": "C000659",
    "Name": "Nelson Adrian Diaz Mejia",
    "Legal Name [Official Company Name]": "Nelson Adrian Diaz Mejia",
    "Industries": "Law",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "11/28/19",
    "Client Last Project Date": "11/29/19",
    "Client First Project Date": "11/29/19",
    "Client First Quote Date": "11/29/19",
    "Client Last Quote Date": "11/29/19",
    "Address 1": "18",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000660",
    "Name": "KKF Consulting office LTD",
    "Legal Name [Official Company Name]": "KKF Consulting office LTD",
    "Industries": "Consulting",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "12/2/19",
    "Client Last Project Date": "12/2/19",
    "Client First Project Date": "12/2/19",
    "Client First Quote Date": "12/2/19",
    "Client Last Quote Date": "12/2/19",
    "Last Modification": "2019-12-02 13:43 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000661",
    "Name": "CARDET LTD",
    "Legal Name [Official Company Name]": "CARDET LTD",
    "Industries": "eLearning",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "LinkedIn",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "12/2/19",
    "Client First Quote Date": "12/2/19",
    "Client Last Quote Date": "12/2/19",
    "Last Modification": "2019-12-02 15:30 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000662",
    "Name": "Libertex Group",
    "Legal Name [Official Company Name]": "Libertex Group",
    "Industries": "Forex",
    "Account Manager": "Yara\tTytarenko",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "12/4/19",
    "Client Last Project Date": "5/6/20",
    "Client First Project Date": "1/30/20",
    "Client First Quote Date": "12/4/19",
    "Client Last Quote Date": "5/6/20",
    "Last Modification": "2020-05-08 16:32 EEST"
  },
  {
    "ID": "C000663",
    "Name": "COLUMBIA SHIPMANAGEMENT LTD",
    "Legal Name [Official Company Name]": "COLUMBIA SHIPMANAGEMENT LTD",
    "Industries": "Transport & Infrastructure",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "12/4/19",
    "Client First Quote Date": "12/4/19",
    "Client Last Quote Date": "12/4/19",
    "Last Modification": "2019-12-04 14:31 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000664",
    "Name": "Nettikasinot",
    "Legal Name [Official Company Name]": "Nettikasinot",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "12/9/19",
    "Client First Quote Date": "12/9/19",
    "Client Last Quote Date": "12/9/19",
    "Last Modification": "2019-12-09 10:24 EET"
  },
  {
    "ID": "C000665",
    "Name": "SODEXO",
    "Legal Name [Official Company Name]": "SODEXO",
    "Industries": "eLearning",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "LinkedIn",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "12/10/19",
    "Client First Quote Date": "12/10/19",
    "Client Last Quote Date": "12/10/19",
    "Last Modification": "2019-12-10 15:18 EET",
    "Country": "France [FR]"
  },
  {
    "ID": "C000669",
    "Name": "Easy Technology",
    "Legal Name [Official Company Name]": "Easy Technology",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "12/24/19",
    "Client First Quote Date": "12/24/19",
    "Client Last Quote Date": "12/24/19",
    "Last Modification": "2019-12-24 15:39 EET"
  },
  {
    "ID": "C000670",
    "Name": "Abbeygate Insurance",
    "Legal Name [Official Company Name]": "Abbeygate Insurance",
    "Industries": "Insurance",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/3/20",
    "Client Last Project Date": "1/3/20",
    "Client First Project Date": "1/3/20",
    "Client First Quote Date": "1/3/20",
    "Client Last Quote Date": "1/3/20",
    "Last Modification": "2020-01-03 13:44 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000673",
    "Name": "Sam Mansour",
    "Legal Name [Official Company Name]": "Sam Mansour",
    "Industries": "Other",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/13/20",
    "Client Last Project Date": "1/13/20",
    "Client First Project Date": "1/13/20",
    "Client First Quote Date": "1/13/20",
    "Client Last Quote Date": "1/13/20",
    "Last Modification": "2020-01-14 10:40 EET",
    "Address 1": "Toumazou Andreas Augustinou 4B",
    "City": "Limassol",
    "Country": "Cyprus [CY]",
    "Postal Code": "3086"
  },
  {
    "ID": "C000674",
    "Name": "Nerdytec",
    "Legal Name [Official Company Name]": "Nerdytec",
    "Industries": "iGaming",
    "Account Manager": "Amarita Sohal",
    "Lead Source": "Cold call",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/13/20",
    "Client Last Project Date": "5/7/20",
    "Client First Project Date": "1/13/20",
    "Client First Quote Date": "1/13/20",
    "Client Last Quote Date": "5/7/20",
    "Last Modification": "2020-05-07 18:31 EEST",
    "Address 1": "Zum Scheider Feld 10",
    "City": "Bergisch Gladbach",
    "Country": "Germany [DE]",
    "Postal Code": "51467"
  },
  {
    "ID": "C000676",
    "Name": "Game Revenue",
    "Legal Name [Official Company Name]": "Game Revenue",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Trade show",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/17/20",
    "Last Modification": "2020-01-17 15:57 EET"
  },
  {
    "ID": "C000678",
    "Name": "AdsVentures",
    "Legal Name [Official Company Name]": "AdsVentures",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/20/20",
    "Client Last Project Date": "1/23/20",
    "Client First Project Date": "1/23/20",
    "Client First Quote Date": "1/21/20",
    "Client Last Quote Date": "1/21/20",
    "Last Modification": "2020-01-20 15:21 EET"
  },
  {
    "ID": "C000681",
    "Name": "Circus Street",
    "Legal Name [Official Company Name]": "Circus Street",
    "Industries": "eLearning",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Monthly Invoice",
    "First Contact Date2": "1/22/20",
    "Client First Quote Date": "1/23/20",
    "Client Last Quote Date": "1/29/20",
    "Last Modification": "2020-01-23 10:46 EET",
    "Country": "United Kingdom [GB]"
  },
  {
    "ID": "C000682",
    "Name": "Initial Merit Secure Ltd (ex Nextrade Worldwide Ltd)",
    "Legal Name [Official Company Name]": "Initial Merit Secure Ltd (ex Nextrade Worldwide Ltd)",
    "Industries": "Forex",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Website",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/24/20",
    "Client Last Project Date": "1/24/20",
    "Client First Project Date": "1/24/20",
    "Client First Quote Date": "1/24/20",
    "Client Last Quote Date": "1/24/20",
    "Last Modification": "2020-01-24 09:59 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000683",
    "Name": "Colmex Pro",
    "Legal Name [Official Company Name]": "Colmex Pro",
    "Industries": "Forex",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/24/20",
    "Client Last Project Date": "5/7/20",
    "Client First Project Date": "1/24/20",
    "Client First Quote Date": "1/24/20",
    "Client Last Quote Date": "5/7/20",
    "Last Modification": "2020-01-24 13:17 EET"
  },
  {
    "ID": "C000684",
    "Name": "AndrÃ©s Ospina",
    "Legal Name [Official Company Name]": "AndrÃ©s Ospina",
    "Industries": "Consulting",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/27/20",
    "Client Last Project Date": "1/27/20",
    "Client First Project Date": "1/27/20",
    "Client First Quote Date": "1/27/20",
    "Client Last Quote Date": "1/27/20",
    "Last Modification": "2020-01-27 15:46 EET"
  },
  {
    "ID": "C000685",
    "Name": "zsuzsanna ignacz",
    "Legal Name [Official Company Name]": "zsuzsanna ignacz",
    "Industries": "Other",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "Adwords",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/28/20",
    "Client Last Project Date": "2/6/20",
    "Client First Project Date": "2/6/20",
    "Client First Quote Date": "1/28/20",
    "Client Last Quote Date": "1/28/20",
    "Last Modification": "2020-01-28 12:03 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000686",
    "Name": "MeMed Diagnostics",
    "Legal Name [Official Company Name]": "MeMed Diagnostics",
    "Industries": "Pharma",
    "Account Manager": "Angelica Nicolaou",
    "Lead Source": "External referral",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "1/28/20",
    "Client Last Project Date": "4/26/20",
    "Client First Project Date": "2/6/20",
    "Client First Quote Date": "1/29/20",
    "Client Last Quote Date": "4/23/20",
    "Last Modification": "2020-02-05 14:48 EET",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000687",
    "Name": "Artem Khorlomov",
    "Legal Name [Official Company Name]": "Artem Khorlomov",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/6/20",
    "Client Last Project Date": "2/6/20",
    "Client First Project Date": "2/6/20",
    "Client First Quote Date": "2/6/20",
    "Client Last Quote Date": "2/6/20",
    "Last Modification": "2020-02-06 14:20 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000688",
    "Name": "Wolfgangs Steakhouse",
    "Legal Name [Official Company Name]": "Wolfgangs Steakhouse",
    "Industries": "Other",
    "Account Manager": "Yara\tTytarenko",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/10/20",
    "Client Last Project Date": "2/28/20",
    "Client First Project Date": "2/28/20",
    "Client First Quote Date": "2/28/20",
    "Client Last Quote Date": "2/28/20",
    "Last Modification": "2020-02-10 12:15 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000689",
    "Name": "Vahab Hasiri",
    "Legal Name [Official Company Name]": "Vahab Hasiri",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/12/20",
    "Client Last Project Date": "2/12/20",
    "Client First Project Date": "2/12/20",
    "Client First Quote Date": "2/12/20",
    "Client Last Quote Date": "2/12/20",
    "Address 1": "13",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000690",
    "Name": "Baluta Alexandru",
    "Legal Name [Official Company Name]": "Baluta Alexandru",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/18/20",
    "Address 1": "27",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000691",
    "Name": "TVBET",
    "Legal Name [Official Company Name]": "Astok Ltd",
    "Industries": "iGaming",
    "Account Manager": "Yara\tTytarenko",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "2/24/20",
    "Client Last Project Date": "3/3/20",
    "Client First Project Date": "3/3/20",
    "Client First Quote Date": "2/24/20",
    "Client Last Quote Date": "2/24/20",
    "Address 1": "Astok LTD 12 Thasou",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000693",
    "Name": "Fernanda Radl",
    "Legal Name [Official Company Name]": "Fernanda Radl",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/3/20",
    "Last Modification": "2020-03-03 14:27 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000694",
    "Name": "ELearning Delta",
    "Legal Name [Official Company Name]": "ELearning Delta",
    "Industries": "eLearning",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "50% Deposit / 50% After Delivery",
    "First Contact Date2": "3/5/20",
    "Client Last Project Date": "3/30/20",
    "Client First Project Date": "3/5/20",
    "Client First Quote Date": "3/2/20",
    "Client Last Quote Date": "3/30/20",
    "Last Modification": "2020-03-05 17:26 EET",
    "Country": "United States [US]"
  },
  {
    "ID": "C000695",
    "Name": "Qi Zheng",
    "Legal Name [Official Company Name]": "Leos Car Rental",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/6/20",
    "Client Last Project Date": "3/6/20",
    "Client First Project Date": "3/6/20",
    "Client First Quote Date": "3/6/20",
    "Client Last Quote Date": "3/6/20",
    "Last Modification": "2020-03-10 16:26 EET",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000696",
    "Name": "Al - Shlouf Mohamed",
    "Legal Name [Official Company Name]": "Al - Shlouf Mohamed",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/6/20",
    "Address 1": "7",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000698",
    "Name": "Panicos Nicolaou",
    "Legal Name [Official Company Name]": "Panicos Nicolaou",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/9/20",
    "Client Last Project Date": "3/9/20",
    "Client First Project Date": "3/9/20",
    "Last Modification": "2020-03-09 17:18 EET",
    "Address 1": "133 Glastonos",
    "City": "Limassol",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000699",
    "Name": "Royal Forex Ltd",
    "Legal Name [Official Company Name]": "Royal Forex Ltd",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/13/20",
    "Client Last Project Date": "3/18/20",
    "Client First Project Date": "3/13/20",
    "Client First Quote Date": "3/13/20",
    "Client Last Quote Date": "3/17/20",
    "Address 1": "Lemesou 128-130",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000701",
    "Name": "HND Construction & Property/ BsC Quantity Surveyor / ACCA",
    "Legal Name [Official Company Name]": "HND Construction & Property/ BsC Quantity Surveyor / ACCA",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/16/20",
    "Client Last Project Date": "3/17/20",
    "Client First Project Date": "3/17/20",
    "Client First Quote Date": "3/16/20",
    "Client Last Quote Date": "3/16/20",
    "Address 1": "Panagioti Papaioannou",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000702",
    "Name": "Rasa Svetaviciute",
    "Legal Name [Official Company Name]": "Rasa Svetaviciute",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/19/20",
    "Client First Quote Date": "3/19/20",
    "Client Last Quote Date": "3/19/20",
    "Address 1": "221 Makariou avenue",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000703",
    "Name": "Rapid Nutrition",
    "Legal Name [Official Company Name]": "Rapid Nutrition",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/23/20",
    "Client Last Project Date": "3/30/20",
    "Client First Project Date": "3/24/20",
    "Client First Quote Date": "3/23/20",
    "Client Last Quote Date": "3/30/20",
    "Last Modification": "2020-03-24 00:02 EET",
    "Country": "Australia [AU]"
  },
  {
    "ID": "C000705",
    "Name": "Web Theoria",
    "Legal Name [Official Company Name]": "Web Thoria",
    "Industries": "Marketing Agency",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "3/31/20",
    "Client Last Project Date": "3/31/20",
    "Client First Project Date": "3/31/20",
    "Client First Quote Date": "3/31/20",
    "Client Last Quote Date": "3/31/20",
    "Address 1": "3",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000706",
    "Name": "Windsor Brokers",
    "Legal Name [Official Company Name]": "Windsor Brokers",
    "Industries": "Forex",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "4/2/20",
    "Client Last Project Date": "4/29/20",
    "Client First Project Date": "4/29/20",
    "Client First Quote Date": "4/2/20",
    "Client Last Quote Date": "4/29/20",
    "Address 1": "Spyrou Kyprianou 53",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000709",
    "Name": "DM Communications",
    "Legal Name [Official Company Name]": "DM Communications",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "4/7/20",
    "Client First Quote Date": "4/8/20",
    "Client Last Quote Date": "4/8/20",
    "Last Modification": "2020-04-08 11:14 EEST",
    "Country": "Israel [IL]"
  },
  {
    "ID": "C000707",
    "Name": "Trio Markets",
    "Legal Name [Official Company Name]": "Trio Markets",
    "Industries": "Forex",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "4/7/20",
    "Client First Quote Date": "4/7/20",
    "Client Last Quote Date": "4/7/20",
    "Last Modification": "2020-04-07 11:13 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000710",
    "Name": "MTNico",
    "Legal Name [Official Company Name]": "MTNico",
    "Industries": "Forex",
    "Account Manager": "Amarita Sohal",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "4/14/20",
    "Client Last Project Date": "4/23/20",
    "Client First Project Date": "4/21/20",
    "Client First Quote Date": "4/17/20",
    "Client Last Quote Date": "4/21/20",
    "Address 1": "Andrea Zappa & Makedonon 4",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000712",
    "Name": "Monlinks Services LTD",
    "Legal Name [Official Company Name]": "Monlinks Services LTD",
    "Industries": "Other",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "4/21/20",
    "Client First Quote Date": "4/21/20",
    "Client Last Quote Date": "4/21/20",
    "Last Modification": "2020-04-21 17:41 EEST",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000715",
    "Name": "OxTraffic Ltd",
    "Legal Name [Official Company Name]": "OxTraffic Ltd",
    "Industries": "iGaming",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/7/20",
    "Last Modification": "2020-05-07 10:08 EEST",
    "City": "Tel Aviv",
    "Country": "Israel [IL]",
    "Postal Code": "6165205"
  },
  {
    "ID": "C000717",
    "Name": "AGRIMIROS LIMITED",
    "Legal Name [Official Company Name]": "AGRIMIROS LIMITED",
    "Industries": "Other",
    "Account Manager": "Angelica Nicolaou",
    "Custom Fields > Client Payment Profile": "Pay Per Project",
    "First Contact Date2": "5/8/20",
    "Address 1": "Limassol Center 7A",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000025",
    "Name": "Gemera Group LP ( Sergey - Barbados",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000039",
    "Name": "Nekstream Global",
    "Legal Name [Official Company Name]": "Nekstream Global",
    "Industries": "Food",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000092",
    "Name": "Forex24 Global",
    "Legal Name [Official Company Name]": "Forex24 Global",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000094",
    "Name": "JFD Brokers",
    "Legal Name [Official Company Name]": "JFD Group Ltd",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000103",
    "Name": "SYNOT Games",
    "Legal Name [Official Company Name]": "SYNOT W",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000128",
    "Name": "MAV Secure",
    "Legal Name [Official Company Name]": "MarketingMore LTD [Toyga]",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000534",
    "Name": "Kapriza",
    "Legal Name [Official Company Name]": "Kapriza",
    "Industries": "Travel",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000546",
    "Name": "Buff.bet",
    "Legal Name [Official Company Name]": "Buff.bet",
    "Industries": "eSport",
    "Account Manager": "Angelica Nicolaou",
    "Country": "Bulgaria [BG]"
  },
  {
    "ID": "C000618",
    "Name": "Simplex.coffee",
    "Legal Name [Official Company Name]": "Simplex.coffee",
    "Industries": "Food",
    "Account Manager": "Angelica Nicolaou",
    "Country": "Cyprus [CY]"
  },
  {
    "ID": "C000641",
    "Name": "Wintrado",
    "Legal Name [Official Company Name]": "Wintrado",
    "Industries": "Finance",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000668",
    "Name": "Esports Kingdom LP",
    "Legal Name [Official Company Name]": "Esports Kingdom LP",
    "Industries": "eSport",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000671",
    "Name": "Pearl Production",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000672",
    "Name": "Ad Astra",
    "Account Manager": "Angelica Nicolaou"
  },
  {
    "ID": "C000677",
    "Name": "ROI Collective",
    "Legal Name [Official Company Name]": "ROI Collective",
    "Industries": "Affiliate",
    "Account Manager": "Angelica Nicolaou"
  }
];

const unifyClients = async () => {
  const pangeaGlobal = await User.findOne({ firstName: 'Pangea' });
  const otherProject = await Industries.findOne({ name: 'Other' });
  for (let client of clients) {
    const street = client['Address 1'] || '';
    const town = client['City'] || '';
    const country = client['Country'] || '';
    const address = `${street && street + ', '}${town && town + ', '}${country && country}`
    const officialName = client['Legal Name [Official Company Name]'];
    const newClient = {
      name: client['Name'],
      website: '',
      contract: '',
      nda: '',
      leadSource: '',
      salesComission: '',
      contactName: '',
      email: '',
      vat: '',
      matrix: {},
      status: 'Active',
      officialName,
      address,
      industries: [ObjectId(otherProject._id)],
      contacts: [
        {
          _id: ObjectId(pangeaGlobal._id),
          email: `${pangeaGlobal.email}`,
          firstName: `${pangeaGlobal.firstName}`,
          surname: `${pangeaGlobal.lastName}`,
          phone: 12345678,
          password: null,
          photo: '/clientsDocs/5c3b1d62b7671e69a7c7a6ad/contacts/Michal-St-900x506.jpeg',
          leadContact: true,
          position: 'Manager'
        },
      ],
      accountManager: {
        _id: `${pangeaGlobal._id}`,
        username: `${pangeaGlobal.username}`,
        firstName: `${pangeaGlobal.firstName}`,
        lastName: `${pangeaGlobal.lastName}`,
        group: {
          name: 'Account Managers',
          _id: `${pangeaGlobal._id}`,
        }
      },
      salesManager: {
        _id: `${pangeaGlobal._id}`,
        username: `${pangeaGlobal.username}`,
        group: {
          name: 'Sales',
          _id: `${pangeaGlobal._id}`,
        },
        firstName: `${pangeaGlobal.firstName}`,
        lastName: `${pangeaGlobal.lastName}`
      },
      projectManager: {
        _id: `${pangeaGlobal._id}`,
        username: `${pangeaGlobal.username}`,
        group: {
          name: 'Project Managers',
          _id: `${pangeaGlobal._id}`,
        },
        firstName: `${pangeaGlobal.firstName}`,
        lastName: `${pangeaGlobal.lastName}`
      },
      hoursRates: [],
      monoRates: [],
      wordsRates: []
    };
    await Clients.updateOne({ name: client['Name'] }, newClient, { upsert: true });
  }
};

module.exports = { unifyClients };
