const defaultClients = [
  {
    name: 'DDD-default',
    website: 'www.ddd.com',
    status: 'Active',
    contract: '',
    nda: '',
    accountManager: 'arans@pangea.global',
    salesManager: 'eirini@pangea-langs.com',
    projectManager: 'illy@pangea.global',
    leadSource: 'Website',
    salesComission: 'Passed threshold',
    officialName: 'DDD LTD',
    contactName: 'Jack Di',
    email: 'ddd@ddd.com',
    vat: '',
    address: '345 DSD Street, Moscow, Russia',
    industries: [{ name: 'Hotel & Real Estates' }],
    billingInfo : {
      vat : false,
      address : '',
      invoiceSending : false,
      startingBalance : 0,
      balance : 0,
      minimumBalance : 0,
      email : 'ddd@ddd.com'
    },
    services: [],
    rates : {
      basicPricesTable : [],
      stepMultipliersTable : [],
      industryMultipliersTable : [],
      pricelistTable : []
    },
    sourceLanguages: [],
    targetLanguages: [],
    contacts: [{
      photo: '',
      firstName: 'Sam',
      surname: 'Nolan',
      email: 'sam@ddd.com',
      gender: 'Male',
      position: 'Manager',
      phone: 12345678,
      skype: 'samNol',
      country: 'Australia',
      timezone: '(UTC+10:00) Canberra, Melbourne, Sydney',
      leadContact: true,
      notes: '',
      password: '$2y$10$uRNbJUwbq7UAtATKTYfCteXIGH788B3utw52fjG2.QnxNRHRo.jBK'
    }]
  },
  {
    name: 'EEE-default',
    website: 'www.eee.com',
    status: 'Active',
    contract: '',
    nda: '',
    accountManager: 'angela@pangea-langs.com',
    salesManager: 'eirini@pangea-langs.com',
    projectManager: 'illy@pangea.global',
    leadSource: 'Internet',
    salesComission: 'Passed threshold',
    officialName: 'EEE LTD',
    contactName: 'Mark Brenson',
    email: 'eee@eee.com',
    vat: '',
    address: 'Old Street, Warsaw, Poland',
    industries: [{ name: 'Legal' }],
    billingInfo : {
      vat : false,
      address : '',
      invoiceSending : false,
      startingBalance : 0,
      balance : 0,
      minimumBalance : 0,
      email : 'eee@eee.com'
    },
    services: [],
    rates : {
      basicPricesTable : [],
      stepMultipliersTable : [],
      industryMultipliersTable : [],
      pricelistTable : []
    },
    sourceLanguages: [],
    targetLanguages: [],
    contacts: [{
      photo: '',
      firstName: 'Ella',
      surname: 'Johns',
      email: 'el@eee.com',
      gender: 'Female',
      position: 'Manager',
      phone: 12345678,
      skype: 'el-jo',
      country: 'Bahamas',
      timezone: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
      leadContact: true,
      notes: '',
      password: '$2y$10$uRNbJUwbq7UAtATKTYfCteXIGH788B3utw52fjG2.QnxNRHRo.jBK'
    }]
  },
  {
    name: 'FFF-default',
    website: 'www.fff.com',
    status: 'Inactive',
    contract: '',
    nda: '',
    accountManager: 'arans@pangea.global',
    salesManager: 'eirini@pangea-langs.com',
    projectManager: 'alexia@pangea-langs.com',
    leadSource: 'Friend',
    salesComission: 'Passed threshold',
    officialName: 'FFF LTD',
    contactName: 'Bruce Lee',
    email: 'fff@fff.com',
    vat: '',
    address: '32 Ave, Seattle WA, USA',
    industries: [{ name: 'CFDs & Online Trading' }],
    billingInfo : {
      vat : false,
      address : '',
      invoiceSending : false,
      startingBalance : 0,
      balance : 0,
      minimumBalance : 0,
      email : 'fff@fff.com'
    },
    services: [],
    rates : {
      basicPricesTable : [],
      stepMultipliersTable : [],
      industryMultipliersTable : [],
      pricelistTable : []
    },
    sourceLanguages: [],
    targetLanguages: [],
    contacts: [{
      photo: '',
      firstName: 'Chen',
      surname: 'Dong',
      email: 'chen@fff.com',
      gender: 'Male',
      position: 'Manager',
      phone: 12345678,
      skype: 'dong',
      country: 'United States of America',
      timezone: '(UTC-06:00) Central America',
      leadContact: true,
      notes: '',
      password: '$2y$10$uRNbJUwbq7UAtATKTYfCteXIGH788B3utw52fjG2.QnxNRHRo.jBK'
    }]
  }
];

module.exports = { defaultClients };
