const defaultLanguages = [
  {
    "lang": "Afrikaans",
    "icon": "/static/flags31x21pix/Afrikaans[AF].png",
    "group": "Afrikaans [AF]",
    "symbol": "AF",
    "xtm": "af_ZA",
    "iso1": "af",
    "iso2": "afr",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "afr"
  },
  {
    "lang": "Amharic",
    "icon": "/static/flags31x21pix/Amharic[AM].png",
    "group": "Amharic [AM]",
    "symbol": "AM",
    "xtm": "am_ET",
    "iso1": "am",
    "iso2": "amh",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "amh"
  },
  {
    "lang": "Macedonian",
    "icon": "/static/flags31x21pix/Macedonian[MK].png",
    "group": "Macedonian [MK]",
    "symbol": "MK",
    "xtm": "mk_MK",
    "iso1": "mk",
    "iso2": "mac (B) mkd (T)",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "mac"
  },
  {
    "lang": "Mongolian",
    "icon": "/static/flags31x21pix/Mongolian[MN].png",
    "group": "Mongolian [MN]",
    "symbol": "MN",
    "xtm": "mn_MN",
    "iso1": "mn",
    "iso2": "mon",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "mon"
  },
  {
    "lang": "Swahili",
    "icon": "/static/flags31x21pix/''Swahili''[SW].png",
    "group": "Swahili [SW]",
    "symbol": "SW",
    "xtm": "sw_SO",
    "iso1": "sw",
    "iso2": "swa",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "swa"
  },
  {
    "lang": "Yoruba",
    "icon": "/static/flags31x21pix/''Yoruba''[YO].png",
    "group": "Yoruba [YO]",
    "symbol": "YO",
    "xtm": "yo_NG",
    "iso1": "yo",
    "iso2": "yor",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "yor"
  },
  {
    "lang": "Zulu",
    "icon": "/static/flags31x21pix/Zulu[ZU].png",
    "group": "Zulu [ZU]",
    "symbol": "ZU",
    "xtm": "zu_ZA",
    "iso1": "zu",
    "iso2": "zul",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "zul"
  },
  {
    "lang": "Hausa",
    "icon": "/static/flags31x21pix/''Hausa''[HA].png",
    "group": "Hausa [HA]",
    "symbol": "HA",
    "xtm": "ha_NG",
    "iso1": "ha",
    "iso2": "hau",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "hau"
  },
  {
    "lang": "Arabic",
    "icon": "/static/flags31x21pix/Arabic[AR].png",
    "group": "Arabic [grouped]",
    "symbol": "AR",
    "xtm": "ar_AA",
    "iso1": "ar-AA",
    "iso2": "ara",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "children": true,
    "memoq": "ara"
  },
  {
    "lang": "Arabic (Morocco)",
    "icon": "/static/flags31x21pix/Arabic[AR-MA].png",
    "group": "Arabic [grouped]",
    "symbol": "AR-MA",
    "xtm": "ar_MA",
    "iso1": "ar-MA",
    "iso2": "ara-MA",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "AR",
    "memoq": "ara-MA"
  },
  {
    "lang": "Arabic (Egypt)",
    "icon": "/static/flags31x21pix/Arabic[AR-EG].png",
    "group": "Arabic [grouped]",
    "symbol": "AR-EG",
    "xtm": "ar_EG",
    "iso1": "ar-EG",
    "iso2": "ara-EG",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "AR",
    "memoq": "ara-EG"
  },
  {
    "lang": "Arabic (Saudi Arabia)",
    "icon": "/static/flags31x21pix/Arabic[AR-SA].png",
    "group": "Arabic [grouped]",
    "symbol": "AR-SA",
    "xtm": "ar_SA",
    "iso1": "ar-SA",
    "iso2": "ara-SA",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "AR",
    "memoq": "ara-SA"
  },
  {
    "lang": "Azerbaijani (Latin)",
    "icon": "/static/flags31x21pix/Azerbaijani[AZ-LN].png",
    "group": "Azerbaijani (Latin) [az-LN]",
    "symbol": "AZ-LN",
    "xtm": "az_AZ_Latn",
    "iso1": "az-AZ-Latin",
    "iso2": "aze",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "aze"
  },
  {
    "lang": "Bulgarian",
    "icon": "/static/flags31x21pix/Bulgarian[BG].png",
    "group": "Bulgarian [BG]",
    "symbol": "BG",
    "xtm": "bg_BG",
    "iso1": "bg-BG",
    "iso2": "bul",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "bul"
  },
  {
    "lang": "Belarusian",
    "icon": "/static/flags31x21pix/Belarusian[BE].png",
    "group": "Belarusian [BE]",
    "symbol": "BE",
    "xtm": "be_BE",
    "iso1": "be",
    "iso2": "bet",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "bet"
  },
  {
    "lang": "Bengali (India)",
    "icon": "/static/flags31x21pix/Bengali[BN-IN].png",
    "group": "Bengali (India) [bn-IN]",
    "symbol": "BN-IN",
    "xtm": "bn_IN",
    "iso1": "bn_IN",
    "iso2": "ben_IN",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "ben-IN"
  },
  {
    "lang": "Bosnian (Cyrillic)",
    "icon": "/static/flags31x21pix/Bosnian[BS].png",
    "group": "Bosnian [BS]",
    "symbol": "BS",
    "xtm": "bs_BA_Cyrl",
    "iso1": "bs",
    "iso2": "bos",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "bos"
  },
  {
    "lang": "Bosnian (Latin)",
    "icon": "/static/flags31x21pix/Bosnian[BS].png",
    "group": "Bosnian [BS]",
    "symbol": "BS-LAT",
    "xtm": "bs_BA_Latn",
    "iso1": "bs-lat",
    "iso2": "bos-lat",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "bos"
  },
  {
    "lang": "Czech",
    "icon": "/static/flags31x21pix/Czech[CS].png",
    "group": "Czech [CS]",
    "symbol": "CS",
    "xtm": "cs_CZ",
    "iso1": "cz-CZ",
    "iso2": "cze",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "cze"
  },
  {
    "lang": "Danish",
    "icon": "/static/flags31x21pix/Danish[DA].png",
    "group": "Danish [da-DK]",
    "symbol": "DA",
    "xtm": "da_DK",
    "iso1": "da-DK",
    "iso2": "dan",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "dan"
  },
  {
    "lang": "Dutch",
    "icon": "/static/flags31x21pix/Dutch[NL].png",
    "group": "Dutch [grouped]",
    "symbol": "NL",
    "xtm": "nl_NL",
    "direction": "both",
    "iso1": "nl",
    "iso2": "dut",
    "crud": false,
    "active": true,
    "check": false,
    "children": true,
    "memoq": "dut"
  },
  {
    "lang": "Flemish",
    "icon": "/static/flags31x21pix/Flemish[NL-BE].png",
    "group": "Flemish [nl-BE]",
    "symbol": "NL-BE",
    "xtm": "nl_BE",
    "iso1": "nl-BE",
    "iso2": "dut-BE",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "NL",
    "memoq": "vls"
  },
  {
    "lang": "Dutch (Netherlands)",
    "icon": "/static/flags31x21pix/Dutch[NL-NL].png",
    "group": "Dutch [grouped]",
    "symbol": "NL-NL",
    "xtm": "nl_NL",
    "iso1": "nl-NL",
    "iso2": "dut-NL",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "NL",
    "memoq": "dut-NL"
  },
  {
    "lang": "German",
    "icon": "/static/flags31x21pix/German[DE].png",
    "group": "German [grouped]",
    "symbol": "DE",
    "xtm": "de_DE",
    "iso1": "de",
    "iso2": "ger",
    "diraction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "children": true,
    "memoq": "ger"
  },
  {
    "lang": "German (Switzerland)",
    "icon": "/static/flags31x21pix/German[DE-CH].png",
    "group": "German [grouped]",
    "symbol": "DE-CH",
    "xtm": "de_CH",
    "iso1": "de-CH",
    "iso2": "ger-CH",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "DE",
    "memoq": "ger-CH"
  },
  {
    "lang": "German (Austria)",
    "icon": "/static/flags31x21pix/German[DE-AT].png",
    "group": "German [grouped]",
    "symbol": "DE-AT",
    "xtm": "de_AT",
    "iso1": "de-AT",
    "iso2": "ger-AT",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "DE",
    "memoq": "ger-AT"
  },
  {
    "lang": "German (Germany)",
    "icon": "/static/flags31x21pix/German[DE-DE].png",
    "group": "German [grouped]",
    "symbol": "DE-DE",
    "xtm": "de_DE",
    "iso1": "de-DE",
    "iso2": "ger-DE",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "DE",
    "memoq": "ger-DE"
  },
  {
    "lang": "Greek",
    "icon": "/static/flags31x21pix/Greek[EL].png",
    "group": "Greek [EL]",
    "symbol": "EL",
    "xtm": "el_GR",
    "iso1": "el-GR",
    "iso2": "gre",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "gre"
  },
  {
    "lang": "English",
    "icon": "/static/flags31x21pix/English[EN-GB].png",
    "group": "English [grouped]",
    "symbol": "EN",
    "xtm": "en_GB",
    "iso1": "en",
    "iso2": "eng",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "children": true,
    "memoq": "eng"
  },
  {
    "lang": "English (United States)",
    "icon": "/static/flags31x21pix/English[EN-US].png",
    "group": "English [grouped]",
    "symbol": "EN-US",
    "xtm": "en_US",
    "iso1": "en-US",
    "iso2": "eng-US",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "EN",
    "memoq": "eng-US"
  },
  {
    "lang": "English (United Kingdom)",
    "icon": "/static/flags31x21pix/English[EN-GB].png",
    "group": "English [grouped]",
    "symbol": "EN-GB",
    "xtm": "en_GB",
    "iso1": "en-GB",
    "iso2": "eng-GB",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "EN",
    "memoq": "eng-GB"
  },
  {
    "lang": "Spanish (Spain)",
    "icon": "/static/flags31x21pix/Spanish[ES-ES].png",
    "group": "Spanish (Spain) [es-ES]",
    "symbol": "ES-ES",
    "xtm": "es_ES",
    "iso1": "es",
    "iso2": "spa-ES",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "spa-ES"
  },
  {
    "lang": "Spanish (Latin America)",
    "icon": "/static/flags31x21pix/Spanish[ES-419].png",
    "group": "Spanish (Latin America) [grouped]",
    "xtm": "es_419",
    "iso1": "es-AR",
    "iso2": "spa-419",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "symbol": "ES-419",
    "children": true,
    "memoq": "spa-M9"
  },
  {
    "lang" : "Spanish (Peru)",
    "group" : "Spanish (Latin America) [grouped]",
    "icon" : "",
    "symbol" : "ES-PE",
    "active" : true,
    "xtm" : "yy",
    "iso1" : "es-pe",
    "iso2" : "spa-PE",
    "children" : false,
    "parent" : "ES-419",
    "china" : "",
    "crud" : false,
    "memoq" : "spa-PE",
    "direction" : "in",
    "check" : false,
    "__v" : 0
  },
  {
    "lang" : "Spanish (Catalan)",
    "group" : "Spanish (Spain) [es-ES]",
    "icon" : "",
    "symbol" : "CAT",
    "active" : true,
    "xtm" : "ca",
    "iso1" : "ca",
    "iso2" : "cat",
    "children" : false,
    "china" : "",
    "crud" : false,
    "memoq" : "cat",
    "direction" : "both",
    "check" : false,
    "parent" : "",
  },
  {
    "lang": "Spanish (Argentina)",
    "icon": "/static/flags31x21pix/Spanish[ES-AR].png",
    "group": "Spanish (Latin America) [grouped]",
    "symbol": "ES-AR",
    "xtm": "es_AR",
    "iso1": "es-AR",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "ES-419",
    "memoq": "spa-AR"
  },
  {
    "lang": "Spanish (Mexico)",
    "symbol": "ES-MX",
    "xtm": "es_MX",
    "iso1": "es-MX",
    "icon": "/static/flags31x21pix/Spanish[ES-MX].png",
    "group": "Spanish (Latin America) [grouped]",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "ES-419",
    "memoq": "spa-MX"
  },
  {
    "lang": "Spanish (Colombian)",
    "symbol": "ES-CO",
    "xtm": "es_CO",
    "iso1": "es-CO",
    "iso2": "spa-CO",
    "icon": "/static/flags31x21pix/Spanish[ES-CO].png",
    "group": "Spanish (Latin America) [grouped]",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "memoq": "spa-CO"
  },
  {
    "lang": "Estonian",
    "icon": "/static/flags31x21pix/Estonian[ET].png",
    "group": "Estonian [ET]",
    "symbol": "ET",
    "xtm": "et_EE",
    "iso1": "et-EE",
    "iso2": "est",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "est"
  },
  {
    "lang": "Farsi (Persian)",
    "icon": "/static/flags31x21pix/Farsi[FA].png",
    "group": "Farsi (Persian) [FA]",
    "symbol": "FA",
    "xtm": "fa_IR",
    "iso1": "fa-IR",
    "iso2": "ger",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "fas"
  },
  {
    "lang": "Finnish",
    "icon": "/static/flags31x21pix/Finnish[FI].png",
    "group": "Finnish [FI]",
    "symbol": "FI",
    "xtm": "fi_FI",
    "iso1": "fi-FI",
    "iso2": "fin",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "fin"
  },
  {
    "lang": "French",
    "icon": "/static/flags31x21pix/French[FR-FR].png",
    "group": "French (EU) [grouped]",
    "symbol": "FR",
    "xtm": "fr_FR",
    "iso1": "fr",
    "iso2": "fre",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "children": true,
    "memoq": "fre"
  },
  {
    "lang": "French (France)",
    "icon": "/static/flags31x21pix/French[FR-FR].png",
    "group": "French (EU) [grouped]",
    "symbol": "FR-FR",
    "xtm": "fr_FR",
    "iso1": "fr-FR",
    "iso2": "fre-FR",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "FR",
    "memoq": "fre-FR"
  },
  {
    "lang": "French (Belgium)",
    "icon": "/static/flags31x21pix/French[FR-BE].png",
    "group": "French (EU) [grouped]",
    "symbol": "FR-BE",
    "xtm": "fr_BE",
    "iso1": "fr-BE",
    "iso2": "fre-BE",
    "direction": "both",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "FR",
    "memoq": "fre-BE"
  },
  {
    "lang": "French (Canada)",
    "icon": "/static/flags31x21pix/French[FR-CA].png",
    "group": "French (Canada) [fr-CA]",
    "symbol": "FR-CA",
    "xtm": "fr_CA",
    "iso1": "fr-CA",
    "iso2": "fre-CA",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "FR",
    "memoq": "fre-CA"
  },
  {
    "lang": "French (Switzerland)",
    "icon": "/static/flags31x21pix/French[FR-CH].png",
    "group": "French (EU) [grouped]",
    "symbol": "FR-CH",
    "xtm": "fr_CH",
    "iso1": "fr-CH",
    "iso2": "fre-CH",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "FR",
    "memoq": "fre-CH"
  },
  {
    "lang": "Hebrew",
    "icon": "/static/flags31x21pix/Hebrew[HE].png",
    "group": "Hebrew [HE]",
    "symbol": "HE",
    "xtm": "he_IL",
    "iso1": "he-IL",
    "iso2": "heb",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "heb"
  },
  {
    "lang": "Hindi",
    "icon": "/static/flags31x21pix/Hindi[HI].png",
    "group": "Hindi [hi-IN]",
    "symbol": "HI",
    "xtm": "hi_IN",
    "iso1": "hi-IN",
    "iso2": "hin",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "hin"
  },
  {
    "lang": "Croatian",
    "icon": "/static/flags31x21pix/Croatian[HR].png",
    "group": "Croatian [HR]",
    "symbol": "HR",
    "xtm": "hr_HR",
    "iso1": "hr-HR",
    "iso2": "hrv",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "hrv"
  },
  {
    "lang": "Hungarian",
    "icon": "/static/flags31x21pix/Hungarian[HU].png",
    "group": "Hungarian [grouped]",
    "symbol": "HU",
    "xtm": "hu_HU",
    "iso1": "hu-HU",
    "iso2": "hun",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "hun"
  },
  {
    "lang": "Armenian",
    "icon": "/static/flags31x21pix/Armenian[HY].png",
    "group": "Armenian [HY]",
    "symbol": "HY",
    "xtm": "hy_AM",
    "iso1": "hy-AM",
    "iso2": "hye",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "hye"
  },
  {
    "lang": "Indonesian",
    "icon": "/static/flags31x21pix/Indonesian[ID].png",
    "group": "Indonesian [id-ID]",
    "symbol": "ID",
    "xtm": "id_ID",
    "iso1": "id-ID",
    "iso2": "ind",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "ind"
  },
  {
    "lang": "Icelandic",
    "icon": "/static/flags31x21pix/Icelandic[IS].png",
    "group": "Icelandic [IS]",
    "symbol": "IS",
    "xtm": "is_IS",
    "iso1": "is-IS",
    "iso2": "ice",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "ice"
  },
  {
    "lang": "Italian",
    "icon": "/static/flags31x21pix/Italian[IT].png",
    "group": "Italian [grouped]",
    "symbol": "IT",
    "xtm": "it_IT",
    "iso1": "it",
    "iso2": "ita",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "children": true,
    "memoq": "ita"
  },
  {
    "lang": "Italian (Italy)",
    "icon": "/static/flags31x21pix/Italian[IT-IT].png",
    "group": "Italian [grouped]",
    "symbol": "IT-IT",
    "xtm": "it_IT",
    "iso1": "it-IT",
    "iso2": "ita-IT",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "IT",
    "memoq": "ita-IT"
  },
  {
    "lang": "Italian (Switzerland)",
    "icon": "/static/flags31x21pix/Italian[IT-CH].png",
    "group": "Italian [grouped]",
    "symbol": "IT-CH",
    "xtm": "it_CH",
    "iso1": "it-CH",
    "iso2": "ita-CH",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "parent": "IT",
    "memoq": "ita-CH"
  },
  {
    "lang": "Japanese",
    "icon": "/static/flags31x21pix/Japanese[JA].png",
    "group": "Japanese [ja-JP]",
    "symbol": "JA",
    "xtm": "ja_JP",
    "iso1": "ja-JP",
    "iso2": "jpn",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "jpn"
  },
  {
    "lang": "Georgian",
    "icon": "/static/flags31x21pix/Georgian[KA].png",
    "group": "Georgian [KA]",
    "symbol": "KA",
    "xtm": "ka_GE",
    "iso1": "ka-GE",
    "iso2": "kat",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "kat"
  },
  {
    "lang": "Kazakh",
    "icon": "/static/flags31x21pix/Kazakh[KK].png",
    "group": "Kazakh [KK]",
    "symbol": "KK",
    "xtm": "kk_KZ",
    "iso1": "kk-KZ",
    "iso2": "kaz",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "kaz"
  },
  {
    "lang": "Korean",
    "icon": "/static/flags31x21pix/Korean[KO].png",
    "group": "Korean [KO]",
    "symbol": "KO",
    "xtm": "ko_KR",
    "iso1": "ko-KR",
    "iso2": "kor",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "kor"
  },
  {
    "lang": "Lithuanian",
    "icon": "/static/flags31x21pix/Lithuanian[LT].png",
    "group": "Lithuanian [LT]",
    "symbol": "LT",
    "xtm": "lt_LT",
    "iso1": "lt-LT",
    "iso2": "lit",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "lit"
  },
  {
    "lang": "Latvian",
    "icon": "/static/flags31x21pix/Latvian[LV].png",
    "group": "Latvian [LV]",
    "symbol": "LV",
    "xtm": "lv_LV",
    "iso1": "lv-LV",
    "iso2": "lav",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "lav"
  },
  {
    "lang": "Moldavian",
    "icon": "/static/flags31x21pix/Moldavian[MO].png",
    "group": "Moldavian [MO]",
    "symbol": "MO",
    "xtm": "mo_MD",
    "iso1": "mo-MD",
    "iso2": "mol",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "mol"
  },
  {
    "lang": "Marathi",
    "icon": "/static/flags31x21pix/Marathi[MR].png",
    "group": "Marathi [MR]",
    "symbol": "MR",
    "xtm": "mr_IN",
    "iso1": "mr-IN",
    "iso2": "mar",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "mar"
  },
  {
    "lang": "Malay",
    "icon": "/static/flags31x21pix/Malay[MS].png",
    "group": "Malay [grouped]",
    "symbol": "MS",
    "xtm": "ms_MY",
    "iso1": "ms-MY",
    "iso2": "msa",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "msa"
  },
  {
    "lang": "Norwegian (Bokmaal)",
    "icon": "/static/flags31x21pix/Norwegian[NB].png",
    "group": "Norwegian (Bokmaal) [grouped]",
    "symbol": "NB",
    "xtm": "nb_NO",
    "iso1": "nb-NO",
    "iso2": "nnb",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "nnb"
  },
  {
    "lang": "Punjabi",
    "icon": "/static/flags31x21pix/Punjabi[PA].png",
    "group": "Punjabi [PA]",
    "symbol": "PA",
    "xtm": "pa_PA",
    "iso1": "pa-PA",
    "iso2": "pan",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "pan"
  },
  {
    "lang": "Polish",
    "icon": "/static/flags31x21pix/Polish[PL].png",
    "group": "Polish [grouped]",
    "symbol": "PL",
    "xtm": "pl_PL",
    "iso1": "pl",
    "iso2": "pol",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "pol"
  },
  {
    "lang": "Portuguese (Brazil)",
    "icon": "/static/flags31x21pix/Portuguese[PT-BR].png",
    "group": "Portuguese (Brazil) [pt-BR]",
    "symbol": "PT-BR",
    "xtm": "pt_BR",
    "iso1": "pt-BR",
    "iso2": "por-BR",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "por-BR"
  },
  {
    "lang": "Portuguese (Portugal)",
    "icon": "/static/flags31x21pix/Portuguese[PT-PT].png",
    "group": "Portuguese (Portugal) [pt-PT]",
    "symbol": "PT-PT",
    "xtm": "pt_PT",
    "iso1": "pt-PT",
    "iso2": "por-PT",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "por-PT"
  },
  {
    "lang": "Romanian",
    "icon": "/static/flags31x21pix/Romanian[RO].png",
    "group": "Romanian [ro-RO]",
    "symbol": "RO",
    "xtm": "ro_RO",
    "iso1": "ro-RO",
    "iso2": "rum",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "rum"
  },
  {
    "lang": "Russian",
    "icon": "/static/flags31x21pix/Russian[RU].png",
    "group": "Russian [ru-RU]",
    "symbol": "RU",
    "xtm": "ru_RU",
    "iso1": "ru-RU",
    "iso2": "rus",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "rus"
  },
  {
    "lang": "Slovak",
    "icon": "/static/flags31x21pix/Slovak[SK].png",
    "group": "Slovak [SK]",
    "symbol": "SK",
    "xtm": "sk_SK",
    "iso1": "sk-SK",
    "iso2": "slo",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "slo"
  },
  {
    "lang": "Slovenian",
    "icon": "/static/flags31x21pix/Slovenian[SL].png",
    "group": "Slovenian [SL]",
    "symbol": "SL",
    "xtm": "sl_SL",
    "iso1": "sl-SL",
    "iso2": "slv",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "slv"
  },
  {
    "lang": "Serbian (Latin)",
    "icon": "/static/flags31x21pix/Serbian[SR-LA].png",
    "group": "Serbian (Latin) [sr-LA]",
    "symbol": "SR-LA",
    "xtm": "sr_RS_Latn",
    "iso1": "sr-LA",
    "iso2": "scr",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "scr"
  },
  {
    "lang": "Swedish (Sweden)",
    "icon": "/static/flags31x21pix/Swedish[SV-SE].png",
    "group": "Swedish (Sweden) [sv-SE]",
    "symbol": "SV-SE",
    "xtm": "sv_SE",
    "iso1": "sv-SE",
    "iso2": "swe-SE",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "swe-SE"
  },
  {
    "lang": "Telugu",
    "symbol": "TE",
    "icon": "/static/flags31x21pix/Telugu[TE].png",
    "group": "Telugu [TE]",
    "xtm": "te_IN",
    "iso1": "te-IN",
    "iso2": "tel",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "tel"
  },
  {
    "lang": "Thai",
    "icon": "/static/flags31x21pix/Thai[TH].png",
    "group": "Thai [TH]",
    "symbol": "TH",
    "xtm": "th_TH",
    "iso1": "th-TH",
    "iso2": "tai",
    "direction": "both",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "tha"
  },
  {
    "lang": "Turkmen",
    "icon": "/static/flags31x21pix/Turkmen[TK].png",
    "group": "Turkmen [TK]",
    "symbol": "TK",
    "xtm": "tk_TM",
    "iso1": "tk-TM",
    "iso2": "tuk",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "tuk"
  },
  {
    "lang": "Tagalog",
    "icon": "/static/flags31x21pix/Tagalog[TL].png",
    "group": "Tagalog [grouped]",
    "symbol": "TL",
    "xtm": "tl_PH",
    "iso1": "tl-PH",
    "iso2": "tgl",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "tgl"
  },
  {
    "lang": "Turkish",
    "icon": "/static/flags31x21pix/Turkish[TR].png",
    "group": "Turkish [tr-TR]",
    "symbol": "TR",
    "xtm": "tr_TR",
    "iso1": "tr-TR",
    "iso2": "tur",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "tur"
  },
  {
    "lang": "Ukrainian",
    "icon": "/static/flags31x21pix/Ukrainian[UK].png",
    "group": "Ukrainian [UK]",
    "symbol": "UK",
    "xtm": "uk_UA",
    "iso1": "uk-UA",
    "iso2": "ukr",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "ukr"
  },
  {
    "lang": "Urdu",
    "icon": "/static/flags31x21pix/Urdu[UR].png",
    "group": "Urdu [UR]",
    "symbol": "UR",
    "xtm": "ur_IN",
    "iso1": "ur-IN",
    "iso2": "urd",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "urd"
  },
  {
    "lang": "Uzbek",
    "icon": "/static/flags31x21pix/Uzbek[UZ].png",
    "group": "Uzbek [UZ]",
    "symbol": "UZ",
    "xtm": "uz",
    "iso1": "uz-UZ-Latn",
    "iso2": "uzb",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "uzb"
  },
  {
    "lang": "Vietnamese",
    "icon": "/static/flags31x21pix/Vietnamese[VI].png",
    "group": "Vietnamese [vi-VN]",
    "symbol": "VI",
    "xtm": "vi_VN",
    "iso1": "vi-VN",
    "iso2": "vie",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "vie"
  },
  {
    "lang": "Chinese",
    "icon": "/static/flags31x21pix/ChineseTraditional[ZH-CN].png",
    "group": "Chinese Simplified [grouped]",
    "symbol": "ZH",
    "xtm": "zho",
    "iso1": "zh",
    "iso2": "zho",
    "direction": "in",
    "crud": false,
    "active": true,
    "children": true,
    "memoq": "zho"
  },
  {
    "lang": "Chinese Simplified",
    "icon": "/static/flags31x21pix/ChineseSimplified[ZH-CN].png",
    "group": "Chinese Simplified [grouped]",
    "symbol": "ZH-CN",
    "xtm": "zh_VN",
    "iso1": "zh-CN",
    "iso2": "zho-CN",
    "direction": "in",
    "crud": false,
    "children" : false,
    "parent" : "ZH",
    "active": true,
    "memoq": "zho-CN"
  },
  {
    "lang": "Chinese (China)",
    "icon": "/static/flags31x21pix/Chinese[ZH-CN].png",
    "group": "Chinese Simplified [grouped]",
    "symbol": "ZH-CN",
    "xtm": "zh_CN",
    "iso1": "zh-CN",
    "iso2": "zho-CN",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "children" : false,
    "parent" : "ZH",
    "china": "simplified",
    "memoq": "zho-CN"
  },
  {
    "lang": "Chinese (Singapore)",
    "icon": "/static/flags31x21pix/Chinese[ZH-SG].png",
    "group": "Chinese Simplified [grouped]",
    "symbol": "ZH-SG",
    "xtm": "zh_SG",
    "iso1": "zh-SG",
    "iso2": "zho-SG",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "children" : false,
    "parent" : "ZH",
    "china": "simplified",
    "memoq": "zho-SG"
  },
  {
    "lang": "Chinese (Hong Kong)",
    "icon": "/static/flags31x21pix/Chinese[ZH-HK].png",
    "group": "Chinese Traditional [grouped]",
    "symbol": "ZH-HK",
    "xtm": "zh_HK",
    "iso1": "zh-HK",
    "iso2": "zho-HK",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "children" : false,
    "parent" : "ZH",
    "china": "traditional",
    "memoq": "zho-HK"
  },
  {
    "lang": "Chinese (Macao)",
    "icon": "/static/flags31x21pix/Chinese[ZH-MO].png",
    "group": "Chinese Traditional [grouped]",
    "symbol": "ZH-MO",
    "xtm": "zh_TW",
    "iso1": "zh-MO",
    "iso2": "zho-MO",
    "direction": "in",
    "crud": false,
    "active": true,
    "children" : false,
    "parent" : "ZH",
    "china": "traditional",
    "memoq": "zho-MO"
  },
  {
    "lang": "Chinese (Taiwan)",
    "icon": "/static/flags31x21pix/Chinese[ZH-TW].png",
    "group": "Chinese Traditional [grouped]",
    "symbol": "ZH-TW",
    "xtm": "goyu",
    "iso1": "zh-TW",
    "iso2": "zho-TW",
    "direction": "in",
    "crud": false,
    "check": false,
    "active": true,
    "children" : false,
    "parent" : "ZH",
    "china": "traditional",
    "memoq": "zho-TW"
  },
  {
    "lang": "Burmese",
    "icon": "/static/flags31x21pix/Burmese[BU].png",
    "group": "Burmese [my-MM]",
    "symbol": "BU",
    "xtm": "",
    "iso1": "my",
    "iso2": "bur(B) mya(T)",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "mya"
  },
  {
    "lang": "Filipino",
    "icon": "/static/flags31x21pix/Filipino[FIL].png",
    "group": "Tagalog [grouped]",
    "symbol": "FIL",
    "xtm": "",
    "iso1": "",
    "iso2": "fil",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "fil"
  },
  {
    "lang": "Haitian Creole",
    "icon": "/static/flags31x21pix/Haitian[HT].png",
    "group": "Haitian Creole [HT]",
    "symbol": "HT",
    "xtm": "",
    "iso1": "ht",
    "iso2": "hti",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "hti"
  },
  {
    "lang": "Khmer",
    "icon": "/static/flags31x21pix/Khmer[KM].png",
    "group": "Khmer (Cambodian) [KM]",
    "symbol": "KM",
    "xtm": "",
    "iso1": "km",
    "iso2": "khm",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "khm"
  },
  {
    "lang": "Kurdish (Arabic)",
    "icon": "/static/flags31x21pix/Kurdish[KU].png",
    "group": "Kurdish (Arabic) [KU]",
    "symbol": "KU",
    "xtm": "",
    "iso1": "ku",
    "iso2": "kur",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "ckb"
  },
  {
    "lang": "Lao",
    "icon": "/static/flags31x21pix/Lao[LO].png",
    "group": "Lao [LO]",
    "symbol": "LO",
    "xtm": "",
    "iso1": "lo",
    "iso2": "lao",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "lao"
  },
  {
    "lang": "Maltese",
    "icon": "/static/flags31x21pix/Maltese[MT].png",
    "group": "Maltese [MT]",
    "symbol": "MT",
    "xtm": "",
    "iso1": "mt",
    "iso2": "mlt",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "mlt"
  },
  {
    "lang": "Nepali",
    "icon": "/static/flags31x21pix/Nepali[NE].png",
    "group": "Nepali [NE]",
    "symbol": "NE",
    "xtm": "",
    "iso1": "ne",
    "iso2": "nep",
    "direction": "in",
    "crud": false,
    "active": true,
    "check": false,
    "memoq": "nep"
  },
  {
    "lang" : "Sesotho",
    "group" : "Sesotho [ST]",
    "icon" : "/static/flags31x21pix/''Sesotho''[ST].png",
    "symbol" : "ST",
    "active" : true,
    "xtm" : "",
    "iso1" : "st",
    "iso2" : "sot",
    "children" : false,
    "parent" : "",
    "china" : "",
    "crud" : false,
    "memoq" : "sot",
    "direction" : "both",
    "check" : false,
  },
  {
    "lang" : "Xhosa",
    "group" : "Xhosa [xh_ZA]",
    "icon" : "/static/flags31x21pix/''Xhosa''[XH].png",
    "symbol" : "XH_ZA",
    "active" : true,
    "xtm" : "",
    "iso1" : "xh",
    "iso2" : "xho",
    "children" : false,
    "parent" : "",
    "china" : "",
    "crud" : false,
    "memoq" : "xho",
    "direction" : "both",
    "check" : false,
  }
];

module.exports = { defaultLanguages };
