const defaultServices = [
  {
    sortIndex: 1,
    xtrf: 11,
    symbol: 'tr',
    formType: 'Translation',
    icon: '/static/services/Translation_Localization.png',
    'active': true,
    'crud': false,
    languageForm: 'Duo',
    projectType: 'regular',
    title: 'Translation',
    source: true,
    steps: [],
  },
  {
    sortIndex: 2,
    xtrf: 11,
    symbol: 'lo',
    formType: 'Translation',
    icon: '/static/services/Translation_Localization.png',
    'active': true,
    'crud': false,
    languageForm: 'Duo',
    projectType: 'regular',
    title: 'Localization',
    source: true,
    steps: [],
  },
  {
    sortIndex: 3,
    xtrf: 35,
    symbol: 'pr',
    icon: '/static/services/Translation_Localization.png',
    'active': true,
    'crud': false,
    languageForm: 'Duo',
    projectType: 'smart',
    title: 'Proofing',
    source: true,
    steps: [],
  },
  {
    sortIndex: 6,
    xtrf: 11,
    symbol: 'st',
    formType: 'Translation',
    icon: '/static/services/SEO_Blog_Management.png',
    'active': true,
    'crud': false,
    languageForm: 'Duo',
    projectType: 'regular',
    title: 'SEO Translation',
    source: true,
    steps: [],
  },
  {
    sortIndex: 8,
    xtrf: 12,
    symbol: 'qt',
    icon: '/static/services/QA_and_Testing.png',
    'active': true,
    'crud': false,
    languageForm: 'Duo',
    projectType: 'smart',
    title: 'QA and Testing',
    source: true,
    steps: [],
  },
  {
    sortIndex: 9,
    xtrf: 25,
    symbol: 'gl',
    icon: '/static/services/Localized_Graphic_Design.png',
    'active': true,
    'crud': false,
    languageForm: 'Duo',
    projectType: 'smart',
    title: 'Graphic Localization',
    source: true,
    steps: [],
  },
  {
    sortIndex: 4,
    xtrf: 13,
    symbol: 'co',
    icon: '/static/services/Marketing_Copywriting.png',
    'active': true,
    'crud': false,
    languageForm: 'Mono',
    projectType: 'smart',
    title: 'Copywriting',
    source: false,
    steps: [],
  },
  {
    sortIndex: 5,
    xtrf: 13,
    symbol: 'bl',
    icon: '/static/services/Market_Research.png',
    'active': true,
    'crud': false,
    languageForm: 'Mono',
    projectType: 'smart',
    title: 'Blogging',
    source: false,
    steps: [],
  },
  {
    sortIndex: 7,
    xtrf: 13,
    symbol: 'sw',
    icon: '/static/services/SEO_Blog_Management.png',
    'active': true,
    'crud': false,
    languageForm: 'Mono',
    projectType: 'smart',
    title: 'SEO Writing',
    source: false,
    steps: [],
  },
  {
    sortIndex: 10,
    xtrf: 11,
    symbol: 'ot',
    formType: 'Translation',
    icon: '/static/services/Official_Translations.png',
    'active': true,
    'crud': false,
    languageForm: 'Duo',
    projectType: 'regular',
    title: 'Official Translation',
    source: true,
    steps: [],
  },
];

module.exports = { defaultServices }
