export const getCount = state => state.count;
export const isLoggedIn = state => state.isLoggedIn;
export const loading = state => state.isLoading 
export const getVuexServices = state => state.services;
export const getAllLanguages = state => state.languages; 
export const getClients = state => state.customers;
export const getXtmCustomers = state => state.xtmCustomers;
export const getVendors = state => state.vendors;
export const getRatesDuo = state => state.duoRates;
export const getAllProjects = state => state.projects;
export const getCurrentProject = state => state.currentProject;